/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.mycompany.hotel.cliente.presentacion;

import co.mycompany.hotel.cliente.domain.services.HotelService;

/**
 *
 * @author Jose Ricardo
 */
public class PnlAdmJunior extends javax.swing.JPanel {

    private FrmMain panel;
    private HotelService service;
    String usuario;

    /**
     * Creates new form PnlAdm
     */
    public PnlAdmJunior(FrmMain panel, String usuario) {
        this.usuario = usuario;
        this.service = new HotelService();
        this.panel = panel;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoHab = new javax.swing.ButtonGroup();
        pnlAdmPrincipal = new javax.swing.JPanel();
        tbpMadMenu = new javax.swing.JTabbedPane();
        pnlAdmHabitaciones = new javax.swing.JPanel();
        pnlAdmHabMain = new javax.swing.JPanel();
        bgAdmHabCrear = new javax.swing.JRadioButton();
        bgAdmHabModificar = new javax.swing.JRadioButton();
        bgAdmHabEliminar = new javax.swing.JRadioButton();
        bgAdmHabConsultar = new javax.swing.JRadioButton();
        pnlAdmHabControl = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        pnlAdmPrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlAdmPrincipal.setPreferredSize(new java.awt.Dimension(700, 300));

        pnlAdmHabMain.setBorder(javax.swing.BorderFactory.createTitledBorder("Procesos"));

        GrupoHab.add(bgAdmHabCrear);
        bgAdmHabCrear.setText("Crear");
        bgAdmHabCrear.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                bgAdmHabCrearStateChanged(evt);
            }
        });
        bgAdmHabCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bgAdmHabCrearMouseClicked(evt);
            }
        });

        GrupoHab.add(bgAdmHabModificar);
        bgAdmHabModificar.setText("Modificar");
        bgAdmHabModificar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                bgAdmHabModificarStateChanged(evt);
            }
        });

        GrupoHab.add(bgAdmHabEliminar);
        bgAdmHabEliminar.setText("Eliminar");

        GrupoHab.add(bgAdmHabConsultar);
        bgAdmHabConsultar.setText("Consutar");
        bgAdmHabConsultar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                bgAdmHabConsultarStateChanged(evt);
            }
        });
        bgAdmHabConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bgAdmHabConsultarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlAdmHabMainLayout = new javax.swing.GroupLayout(pnlAdmHabMain);
        pnlAdmHabMain.setLayout(pnlAdmHabMainLayout);
        pnlAdmHabMainLayout.setHorizontalGroup(
            pnlAdmHabMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdmHabMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAdmHabMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bgAdmHabEliminar)
                    .addComponent(bgAdmHabModificar)
                    .addComponent(bgAdmHabCrear)
                    .addComponent(bgAdmHabConsultar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAdmHabMainLayout.setVerticalGroup(
            pnlAdmHabMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdmHabMainLayout.createSequentialGroup()
                .addComponent(bgAdmHabCrear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bgAdmHabConsultar)
                .addGap(5, 5, 5)
                .addComponent(bgAdmHabModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bgAdmHabEliminar)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pnlAdmHabControl.setRequestFocusEnabled(false);
        pnlAdmHabControl.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout pnlAdmHabitacionesLayout = new javax.swing.GroupLayout(pnlAdmHabitaciones);
        pnlAdmHabitaciones.setLayout(pnlAdmHabitacionesLayout);
        pnlAdmHabitacionesLayout.setHorizontalGroup(
            pnlAdmHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdmHabitacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAdmHabMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlAdmHabControl, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlAdmHabitacionesLayout.setVerticalGroup(
            pnlAdmHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAdmHabControl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlAdmHabitacionesLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(pnlAdmHabMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        tbpMadMenu.addTab("Habitaciones", pnlAdmHabitaciones);

        jLabel1.setText("Menu Administracion");

        javax.swing.GroupLayout pnlAdmPrincipalLayout = new javax.swing.GroupLayout(pnlAdmPrincipal);
        pnlAdmPrincipal.setLayout(pnlAdmPrincipalLayout);
        pnlAdmPrincipalLayout.setHorizontalGroup(
            pnlAdmPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdmPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbpMadMenu)
                .addContainerGap())
            .addGroup(pnlAdmPrincipalLayout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAdmPrincipalLayout.setVerticalGroup(
            pnlAdmPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdmPrincipalLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbpMadMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAdmPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, 708, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlAdmPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bgAdmHabConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgAdmHabConsultarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bgAdmHabConsultarMouseClicked

    private void bgAdmHabConsultarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_bgAdmHabConsultarStateChanged
        // TODO add your handling code here:
        if (bgAdmHabConsultar.isSelected()) {
            PnlVistaHabitaciones panelHabVista = new PnlVistaHabitaciones();
            pnlAdmHabControl.removeAll();
            pnlAdmHabControl.add(panelHabVista);
            pnlAdmHabControl.repaint();
            pnlAdmHabControl.revalidate();
        }
    }//GEN-LAST:event_bgAdmHabConsultarStateChanged

    private void bgAdmHabCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgAdmHabCrearMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bgAdmHabCrearMouseClicked

    private void bgAdmHabCrearStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_bgAdmHabCrearStateChanged
        // TODO add your handling code here:
        if (bgAdmHabCrear.isSelected()) {
            PnlAdmHabAdd panelHabAdd = new PnlAdmHabAdd(usuario);
            pnlAdmHabControl.removeAll();
            pnlAdmHabControl.add(panelHabAdd);
            pnlAdmHabControl.repaint();
            pnlAdmHabControl.revalidate();
        }
    }//GEN-LAST:event_bgAdmHabCrearStateChanged

    private void bgAdmHabModificarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_bgAdmHabModificarStateChanged
        // TODO add your handling code here:
        if (bgAdmHabModificar.isSelected()) {
            PnlAdmHabModificar panelHabAdd = new PnlAdmHabModificar(usuario);
            pnlAdmHabControl.removeAll();
            pnlAdmHabControl.add(panelHabAdd);
            pnlAdmHabControl.repaint();
            pnlAdmHabControl.revalidate();
        }
    }//GEN-LAST:event_bgAdmHabModificarStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoHab;
    private javax.swing.JRadioButton bgAdmHabConsultar;
    private javax.swing.JRadioButton bgAdmHabCrear;
    private javax.swing.JRadioButton bgAdmHabEliminar;
    private javax.swing.JRadioButton bgAdmHabModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlAdmHabControl;
    private javax.swing.JPanel pnlAdmHabMain;
    private javax.swing.JPanel pnlAdmHabitaciones;
    private javax.swing.JPanel pnlAdmPrincipal;
    private javax.swing.JTabbedPane tbpMadMenu;
    // End of variables declaration//GEN-END:variables
}
