/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.mycompany.hotel.cliente.presentacion;

import co.mycompany.hotel.cliente.domain.services.HotelService;
import co.mycompany.hotel.commons.domain.Habitacion;
import co.mycompany.hotel.commons.domain.Hotel;
import co.mycompany.hotel.commons.domain.Persona;
import co.mycompany.hotel.commons.domain.TipoHabitacion;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Jose Ricardo
 */
public class PnlAdmPersonaAdd extends javax.swing.JPanel {

    private HotelService service;
     private FrmMain panel;
    //private Hotel hotel;
    private String tipousuario;

    /**
     * Creates new form PnlAdmHabAdd
     */
    public PnlAdmPersonaAdd(String usuario) {
        this.tipousuario = usuario;
        service = new HotelService();
        this.service = service;
        //hotel = new Hotel();
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgAdmHabAdd = new javax.swing.JPanel();
        lbAdmPersNombre = new javax.swing.JLabel();
        lbAdmPersDireccion = new javax.swing.JLabel();
        lbAdmPersId = new javax.swing.JLabel();
        txtAdmPersNombre = new javax.swing.JTextField();
        txtAdmPersDir = new javax.swing.JTextField();
        lbAdmPersTelefono = new javax.swing.JLabel();
        btnPersonaAgregar = new javax.swing.JButton();
        txtAdmPersId = new javax.swing.JTextField();
        txtAdmPersTel = new javax.swing.JTextField();
        lbAdmPersUser = new javax.swing.JLabel();
        lbAdmPersClave = new javax.swing.JLabel();
        txtAdmPersContr = new javax.swing.JTextField();
        txtAdmPersUser = new javax.swing.JTextField();

        bgAdmHabAdd.setPreferredSize(new java.awt.Dimension(570, 202));

        lbAdmPersNombre.setText("Nombre");

        lbAdmPersDireccion.setText("Direccion");

        lbAdmPersId.setText("Numero cedula");

        lbAdmPersTelefono.setText("Telefono");

        btnPersonaAgregar.setText("Crear Usuario");
        btnPersonaAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonaAgregarActionPerformed(evt);
            }
        });

        lbAdmPersUser.setText("Usuario");

        lbAdmPersClave.setText("Contraseña nueva");

        javax.swing.GroupLayout bgAdmHabAddLayout = new javax.swing.GroupLayout(bgAdmHabAdd);
        bgAdmHabAdd.setLayout(bgAdmHabAddLayout);
        bgAdmHabAddLayout.setHorizontalGroup(
            bgAdmHabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgAdmHabAddLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(bgAdmHabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgAdmHabAddLayout.createSequentialGroup()
                        .addComponent(lbAdmPersClave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAdmPersContr, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(bgAdmHabAddLayout.createSequentialGroup()
                        .addGroup(bgAdmHabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbAdmPersTelefono)
                            .addComponent(lbAdmPersId)
                            .addComponent(lbAdmPersNombre)
                            .addComponent(lbAdmPersDireccion)
                            .addComponent(lbAdmPersUser))
                        .addGap(18, 18, 18)
                        .addGroup(bgAdmHabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAdmPersNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAdmPersId, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAdmPersDir, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAdmPersTel, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAdmPersUser, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(btnPersonaAgregar)
                        .addGap(19, 19, 19))))
        );
        bgAdmHabAddLayout.setVerticalGroup(
            bgAdmHabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgAdmHabAddLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgAdmHabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAdmPersId)
                    .addComponent(txtAdmPersId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgAdmHabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAdmPersNombre)
                    .addComponent(txtAdmPersNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(bgAdmHabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgAdmHabAddLayout.createSequentialGroup()
                        .addGroup(bgAdmHabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgAdmHabAddLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lbAdmPersDireccion))
                            .addGroup(bgAdmHabAddLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAdmPersDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22)
                        .addGroup(bgAdmHabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbAdmPersTelefono)
                            .addComponent(txtAdmPersTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(bgAdmHabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbAdmPersUser)
                            .addComponent(txtAdmPersUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(bgAdmHabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbAdmPersClave)
                            .addComponent(txtAdmPersContr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bgAdmHabAddLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnPersonaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bgAdmHabAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgAdmHabAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPersonaAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonaAgregarActionPerformed
        // TODO add your handling code here:
        //public Habitacion(int id, String descripcion, int precio, TipoHabitacion tipo);
        int id=Integer.parseInt(txtAdmPersId.getText());
        String nombre = txtAdmPersNombre.getText();
        String telefono = txtAdmPersTel.getText();
        String direccion= txtAdmPersDir.getText();
        String User=txtAdmPersUser.getText();
        String clave=txtAdmPersContr.getText();
        Persona Persona=new Persona(User, clave, id, nombre, telefono, direccion);
        JFrame jFrame = new JFrame();
        JOptionPane.showMessageDialog(jFrame, service.addPersona(Persona, tipousuario));
//        txtAdmHotNombre.setText("");
//        txtAdmHotDir.setText("");
//        txtAdmHotCiudad.setText("");
//        txtAdmHotTel.setText("");
//        txtAdmHabFoto.setText("");
    }//GEN-LAST:event_btnPersonaAgregarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgAdmHabAdd;
    private javax.swing.JButton btnPersonaAgregar;
    private javax.swing.JLabel lbAdmPersClave;
    private javax.swing.JLabel lbAdmPersDireccion;
    private javax.swing.JLabel lbAdmPersId;
    private javax.swing.JLabel lbAdmPersNombre;
    private javax.swing.JLabel lbAdmPersTelefono;
    private javax.swing.JLabel lbAdmPersUser;
    private javax.swing.JTextField txtAdmPersContr;
    private javax.swing.JTextField txtAdmPersDir;
    private javax.swing.JTextField txtAdmPersId;
    private javax.swing.JTextField txtAdmPersNombre;
    private javax.swing.JTextField txtAdmPersTel;
    private javax.swing.JTextField txtAdmPersUser;
    // End of variables declaration//GEN-END:variables
}
