/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.mycompany.hotel.cliente.presentacion;

import co.mycompany.hotel.cliente.domain.services.HotelService;
import co.mycompany.hotel.commons.domain.Habitacion;
import co.mycompany.hotel.commons.domain.Hotel;
import co.mycompany.hotel.commons.domain.TipoHabitacion;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Jose Ricardo
 */
public class PnlHabEliminar extends javax.swing.JPanel {

    private HotelService service;
    private TipoHabitacion tipos[];
    private ArrayList<Hotel> hoteles;
    private String usuario;
    private Habitacion habitacion;

    /**
     * Creates new form PnlAdmHabAdd
     */
    public PnlHabEliminar(String usuario) {
        Habitacion habitacion = new Habitacion();
        this.usuario = usuario;
        service = new HotelService();
        this.service = service;
        hoteles = new ArrayList<>();
        initComponents();
        cargarValoresIniciales();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgAdmHabAdd = new javax.swing.JPanel();
        pnlHabModConsultar = new javax.swing.JPanel();
        lblIdHabitacion = new javax.swing.JLabel();
        btnHabEliBuscarId = new javax.swing.JButton();
        cbxHabEliHoteles = new javax.swing.JComboBox<>();
        txtHabEliId = new javax.swing.JTextField();
        btnHabEliEliminar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbAdmHabDescripcion = new javax.swing.JLabel();
        txtHabEliDescripcion = new javax.swing.JTextField();
        lbAdmHabPrecio = new javax.swing.JLabel();
        txtHabEliPrecio = new javax.swing.JTextField();
        lbAdmHabTipo = new javax.swing.JLabel();
        cbxHabEliTipo = new javax.swing.JComboBox<>();
        btnAdmHabFoto = new javax.swing.JButton();
        txtHabEliFoto = new javax.swing.JTextField();
        lbHabEliTitulo = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(740, 235));

        bgAdmHabAdd.setPreferredSize(new java.awt.Dimension(570, 202));

        pnlHabModConsultar.setBorder(javax.swing.BorderFactory.createTitledBorder("Consular habitación"));
        pnlHabModConsultar.setOpaque(false);

        lblIdHabitacion.setText("Id");

        btnHabEliBuscarId.setText("Buscar");
        btnHabEliBuscarId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabEliBuscarIdActionPerformed(evt);
            }
        });

        cbxHabEliHoteles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtHabEliId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtHabEliIdMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlHabModConsultarLayout = new javax.swing.GroupLayout(pnlHabModConsultar);
        pnlHabModConsultar.setLayout(pnlHabModConsultarLayout);
        pnlHabModConsultarLayout.setHorizontalGroup(
            pnlHabModConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHabModConsultarLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnHabEliBuscarId)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHabModConsultarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlHabModConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHabModConsultarLayout.createSequentialGroup()
                        .addComponent(lblIdHabitacion)
                        .addGap(18, 18, 18)
                        .addComponent(txtHabEliId))
                    .addComponent(cbxHabEliHoteles, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        pnlHabModConsultarLayout.setVerticalGroup(
            pnlHabModConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHabModConsultarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlHabModConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdHabitacion)
                    .addComponent(txtHabEliId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxHabEliHoteles, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(btnHabEliBuscarId)
                .addContainerGap())
        );

        lblIdHabitacion.getAccessibleContext().setAccessibleName("lblIdhotel");

        btnHabEliEliminar.setText("Eliminar Habitacion");
        btnHabEliEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabEliEliminarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datoa encontrados"));
        jPanel1.setOpaque(false);

        lbAdmHabDescripcion.setText("Descripcion");

        lbAdmHabPrecio.setText("Precio");

        lbAdmHabTipo.setText("Tipo");

        cbxHabEliTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAdmHabFoto.setText("Foto");
        btnAdmHabFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmHabFotoActionPerformed(evt);
            }
        });

        txtHabEliFoto.setEnabled(false);
        txtHabEliFoto.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAdmHabTipo)
                    .addComponent(lbAdmHabPrecio)
                    .addComponent(lbAdmHabDescripcion)
                    .addComponent(btnAdmHabFoto))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtHabEliDescripcion)
                    .addComponent(txtHabEliPrecio)
                    .addComponent(cbxHabEliTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtHabEliFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHabEliDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAdmHabDescripcion))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHabEliPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAdmHabPrecio))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxHabEliTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAdmHabTipo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdmHabFoto)
                    .addComponent(txtHabEliFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbHabEliTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbHabEliTitulo.setText("Eliminar habitación");

        javax.swing.GroupLayout bgAdmHabAddLayout = new javax.swing.GroupLayout(bgAdmHabAdd);
        bgAdmHabAdd.setLayout(bgAdmHabAddLayout);
        bgAdmHabAddLayout.setHorizontalGroup(
            bgAdmHabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgAdmHabAddLayout.createSequentialGroup()
                .addGroup(bgAdmHabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgAdmHabAddLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(bgAdmHabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlHabModConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHabEliEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgAdmHabAddLayout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(lbHabEliTitulo)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        bgAdmHabAddLayout.setVerticalGroup(
            bgAdmHabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgAdmHabAddLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbHabEliTitulo)
                .addGap(18, 18, 18)
                .addGroup(bgAdmHabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bgAdmHabAddLayout.createSequentialGroup()
                        .addComponent(pnlHabModConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHabEliEliminar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgAdmHabAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgAdmHabAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnHabEliEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabEliEliminarActionPerformed
        // TODO add your handling code here:
//        public Habitacion(int id, String descripcion, int precio, TipoHabitacion tipo);
        TipoHabitacion tipo = this.tipos[cbxHabEliTipo.getSelectedIndex()];
        String descripcion = txtHabEliDescripcion.getText();
        int precio = Integer.parseInt(txtHabEliPrecio.getText());
        int id = Integer.parseInt(txtHabEliId.getText());

        habitacion.setId(id);
        habitacion.setDescripcion(descripcion);
        habitacion.setPrecio(precio);
        habitacion.setTipo(tipo);
        habitacion.setFoto(txtHabEliFoto.getText());
        JFrame jFrame = new JFrame();
        JOptionPane.showMessageDialog(jFrame, service.ModificarHabitacion(habitacion));
        txtHabEliDescripcion.setText("");
        txtHabEliPrecio.setText("");
        txtHabEliFoto.setText("");

    }//GEN-LAST:event_btnHabEliEliminarActionPerformed

    private void btnAdmHabFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmHabFotoActionPerformed
        // TODO add your handling code here:

        JFileChooser j = new JFileChooser();
        FileNameExtensionFilter fil = new FileNameExtensionFilter("JPG, PNG & GIF", "jpg", "png", "gif");
        j.setFileFilter(fil);

        int s = j.showOpenDialog(this);
        if (s == JFileChooser.APPROVE_OPTION) {
            String ruta = j.getSelectedFile().getAbsolutePath();
            txtHabEliFoto.setText(ruta);
        }
    }//GEN-LAST:event_btnAdmHabFotoActionPerformed

    private void btnHabEliBuscarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabEliBuscarIdActionPerformed
        try {
            int id = Integer.parseInt(txtHabEliId.getText());
            habitacion = service.getHabitacion(id);
            if (habitacion.getId_hotel() == hoteles.get(cbxHabEliHoteles.getSelectedIndex()).getId()) {
                txtHabEliDescripcion.setText(habitacion.getDescripcion());
                txtHabEliPrecio.setText(String.valueOf(habitacion.getPrecio()));
                txtHabEliFoto.setText(habitacion.getFoto());
                btnHabEliEliminar.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(null, "Habitacion no encontrada");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No es un id valido");
        }
    }//GEN-LAST:event_btnHabEliBuscarIdActionPerformed

    private void txtHabEliIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHabEliIdMouseClicked
        // TODO add your handling code here:
        btnHabEliEliminar.setEnabled(false);
        txtHabEliDescripcion.setText("");
        txtHabEliPrecio.setText("");
        txtHabEliFoto.setText("");

    }//GEN-LAST:event_txtHabEliIdMouseClicked

    private void cargarValoresIniciales() {
        btnHabEliEliminar.setEnabled(false);
        TipoHabitacion tipos[] = TipoHabitacion.values();
        this.tipos = tipos;
        cbxHabEliTipo.removeAllItems();
        for (int i = 0; i < tipos.length; i++) {
            cbxHabEliTipo.addItem(tipos[i].toString());
        }

        cbxHabEliHoteles.addItem("Seleccione un hotel");
        String tipo = service.getSecionTipo(usuario);

        if (tipo.equals("Master")) {
            hoteles = service.getHotels("All_Hotels");
        } else {
            hoteles = service.getHotels(usuario);
        }
        cbxHabEliHoteles.removeAllItems();
        if (hoteles != null) {
            for (int i = 0; i < hoteles.size(); i++) {
                cbxHabEliHoteles.addItem(hoteles.get(i).getNombre());
            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgAdmHabAdd;
    private javax.swing.JButton btnAdmHabFoto;
    private javax.swing.JButton btnHabEliBuscarId;
    private javax.swing.JButton btnHabEliEliminar;
    private javax.swing.JComboBox<String> cbxHabEliHoteles;
    private javax.swing.JComboBox<String> cbxHabEliTipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbAdmHabDescripcion;
    private javax.swing.JLabel lbAdmHabPrecio;
    private javax.swing.JLabel lbAdmHabTipo;
    private javax.swing.JLabel lbHabEliTitulo;
    private javax.swing.JLabel lblIdHabitacion;
    private javax.swing.JPanel pnlHabModConsultar;
    private javax.swing.JTextField txtHabEliDescripcion;
    private javax.swing.JTextField txtHabEliFoto;
    private javax.swing.JTextField txtHabEliId;
    private javax.swing.JTextField txtHabEliPrecio;
    // End of variables declaration//GEN-END:variables
}
