/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.mycompany.hotel.cliente.presentacion;

import co.mycompany.hotel.cliente.domain.services.HotelService;
import co.mycompany.hotel.commons.domain.Hotel;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose Ricardo
 */
public class PnlHotelDelete extends javax.swing.JPanel {

    private HotelService service;
    private ArrayList<Hotel> hoteles;
    private String usuario;
    private boolean bandera;

    /**
     * Creates new form PnlAdmHabAdd
     */
    public PnlHotelDelete(String usuario) {
        this.usuario = usuario;
        service = new HotelService();
        hoteles = service.getHotels("All_Hotels");
        initComponents();
        bandera = false;
        btnHotDelEliminar.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHotDelete = new javax.swing.JPanel();
        lbHotDelNombre = new javax.swing.JLabel();
        lbHotDelDireccion = new javax.swing.JLabel();
        lbHotDelCiudad = new javax.swing.JLabel();
        txtHotDelNombre = new javax.swing.JTextField();
        txtHotDelDir = new javax.swing.JTextField();
        lbHotDelTelefono = new javax.swing.JLabel();
        btnHotDelEliminar = new javax.swing.JButton();
        txtHotDelCiudad = new javax.swing.JTextField();
        txtHotDelTel = new javax.swing.JTextField();
        lbHotDelHotelId = new javax.swing.JLabel();
        txtHotDelAdmin = new javax.swing.JTextField();
        lbHotDelAdmin = new javax.swing.JLabel();
        lbHotDelTitulo = new javax.swing.JLabel();
        txtHotDelHotelId = new javax.swing.JTextField();
        btnHotDelBuscar = new javax.swing.JButton();

        pnlHotDelete.setPreferredSize(new java.awt.Dimension(570, 202));

        lbHotDelNombre.setText("Nombre");

        lbHotDelDireccion.setText("Direccion");

        lbHotDelCiudad.setText("Ciudad");

        txtHotDelNombre.setEditable(false);
        txtHotDelNombre.setAutoscrolls(false);
        txtHotDelNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHotDelNombreActionPerformed(evt);
            }
        });

        txtHotDelDir.setEditable(false);

        lbHotDelTelefono.setText("Telefono");

        btnHotDelEliminar.setText("Eliminar");
        btnHotDelEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHotDelEliminarActionPerformed(evt);
            }
        });

        txtHotDelCiudad.setEditable(false);

        txtHotDelTel.setEditable(false);

        lbHotDelHotelId.setText("Id del Hotel");

        txtHotDelAdmin.setEditable(false);

        lbHotDelAdmin.setText("Administrador");

        lbHotDelTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbHotDelTitulo.setText("Eliminar Hotel");

        txtHotDelHotelId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHotDelHotelIdActionPerformed(evt);
            }
        });

        btnHotDelBuscar.setText("Buscar");
        btnHotDelBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHotDelBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlHotDeleteLayout = new javax.swing.GroupLayout(pnlHotDelete);
        pnlHotDelete.setLayout(pnlHotDeleteLayout);
        pnlHotDeleteLayout.setHorizontalGroup(
            pnlHotDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHotDeleteLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnlHotDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbHotDelCiudad)
                    .addComponent(lbHotDelTelefono)
                    .addComponent(lbHotDelDireccion)
                    .addComponent(lbHotDelNombre)
                    .addComponent(lbHotDelAdmin))
                .addGap(28, 28, 28)
                .addGroup(pnlHotDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtHotDelAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(txtHotDelNombre)
                    .addComponent(txtHotDelDir)
                    .addComponent(txtHotDelCiudad)
                    .addComponent(txtHotDelTel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(pnlHotDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnHotDelEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbHotDelHotelId)
                    .addComponent(txtHotDelHotelId)
                    .addComponent(btnHotDelBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(71, 71, 71))
            .addGroup(pnlHotDeleteLayout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(lbHotDelTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHotDeleteLayout.setVerticalGroup(
            pnlHotDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHotDeleteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbHotDelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(pnlHotDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHotDeleteLayout.createSequentialGroup()
                        .addGroup(pnlHotDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHotDelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbHotDelNombre)
                            .addComponent(lbHotDelHotelId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlHotDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlHotDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtHotDelDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbHotDelDireccion))
                            .addComponent(txtHotDelHotelId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlHotDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbHotDelCiudad)
                            .addComponent(txtHotDelCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnHotDelBuscar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(pnlHotDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHotDeleteLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnHotDelEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlHotDeleteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlHotDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbHotDelTelefono)
                            .addComponent(txtHotDelTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlHotDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHotDelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbHotDelAdmin))))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHotDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlHotDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnHotDelEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHotDelEliminarActionPerformed
        // TODO add your handling code here:
        //public Habitacion(int id, String descripcion, int precio, TipoHabitacion tipo);

        try {
            int id = Integer.parseInt(txtHotDelHotelId.getText());
            if (JOptionPane.showConfirmDialog(null,
                    "Esta seguro de eliminar el hotel con id " + id,
                    "Eliminar hotel", JOptionPane.OK_CANCEL_OPTION) == 0) {
                JOptionPane.showMessageDialog(null, service.deleteHotel(id), "Alerta", JOptionPane.INFORMATION_MESSAGE);
            }
            txtHotDelNombre.setText("");
            txtHotDelDir.setText("");
            txtHotDelCiudad.setText("");
            txtHotDelTel.setText("");
            txtHotDelAdmin.setText("");
            btnHotDelEliminar.setEnabled(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Datos invalidos");
        }

    }//GEN-LAST:event_btnHotDelEliminarActionPerformed

    private void txtHotDelNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHotDelNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHotDelNombreActionPerformed

    private void btnHotDelBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHotDelBuscarActionPerformed
        // TODO add your handling code here:

        try {
            int id = Integer.parseInt(txtHotDelHotelId.getText());

            for (Hotel hotel : hoteles) {
                if (hotel.getId() == id) {
                    txtHotDelNombre.setText(hotel.getNombre());
                    txtHotDelDir.setText(hotel.getDirecccion());
                    txtHotDelCiudad.setText(hotel.getCiudad());
                    txtHotDelTel.setText(hotel.getTelefono());
                    txtHotDelAdmin.setText(hotel.getAdministrador());
                    btnHotDelEliminar.setEnabled(true);
                    return;
                }
            }
            JOptionPane.showMessageDialog(null, "No se encontro el id " + id);
            txtHotDelNombre.setText("");
            txtHotDelDir.setText("");
            txtHotDelCiudad.setText("");
            txtHotDelTel.setText("");
            txtHotDelAdmin.setText("");
            btnHotDelEliminar.setEnabled(false);//*/

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Datos invalidos");
        }

    }//GEN-LAST:event_btnHotDelBuscarActionPerformed

    private void txtHotDelHotelIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHotDelHotelIdActionPerformed
        // TODO add your handling code here:
        btnHotDelEliminar.setEnabled(false);
    }//GEN-LAST:event_txtHotDelHotelIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHotDelBuscar;
    private javax.swing.JButton btnHotDelEliminar;
    private javax.swing.JLabel lbHotDelAdmin;
    private javax.swing.JLabel lbHotDelCiudad;
    private javax.swing.JLabel lbHotDelDireccion;
    private javax.swing.JLabel lbHotDelHotelId;
    private javax.swing.JLabel lbHotDelNombre;
    private javax.swing.JLabel lbHotDelTelefono;
    private javax.swing.JLabel lbHotDelTitulo;
    private javax.swing.JPanel pnlHotDelete;
    private javax.swing.JTextField txtHotDelAdmin;
    private javax.swing.JTextField txtHotDelCiudad;
    private javax.swing.JTextField txtHotDelDir;
    private javax.swing.JTextField txtHotDelHotelId;
    private javax.swing.JTextField txtHotDelNombre;
    private javax.swing.JTextField txtHotDelTel;
    // End of variables declaration//GEN-END:variables
}
