/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.mycompany.hotel.cliente.presentacion;

import co.mycompany.hotel.cliente.domain.services.HotelService;
import co.mycompany.hotel.commons.domain.Hotel;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose Ricardo
 */
public class PnlHotelDelete extends javax.swing.JPanel {

    private HotelService service;
    private ArrayList<Hotel> hoteles;
    private String usuario;
    private boolean bandera;

    /**
     * Creates new form PnlAdmHabAdd
     */
    public PnlHotelDelete(String usuario) {
        this.usuario = usuario;
        service = new HotelService();
        hoteles = service.getHotels("All_Hotels");
        initComponents();
        bandera = false;
        btnHotDelEliminar.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHotDelete = new javax.swing.JPanel();
        lbHotDelTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbHotDelHotelId = new javax.swing.JLabel();
        txtHotDelHotelId = new javax.swing.JTextField();
        btnHotDelBuscar = new javax.swing.JButton();
        btnHotDelEliminar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtHotDelNombre = new javax.swing.JTextField();
        txtHotDelDir = new javax.swing.JTextField();
        txtHotDelCiudad = new javax.swing.JTextField();
        txtHotDelTel = new javax.swing.JTextField();
        txtHotDelAdmin = new javax.swing.JTextField();
        lbHotDelNombre = new javax.swing.JLabel();
        lbHotDelDireccion = new javax.swing.JLabel();
        lbHotDelCiudad = new javax.swing.JLabel();
        lbHotDelTelefono = new javax.swing.JLabel();
        lbHotDelAdmin = new javax.swing.JLabel();

        setOpaque(false);

        pnlHotDelete.setOpaque(false);
        pnlHotDelete.setPreferredSize(new java.awt.Dimension(570, 202));

        lbHotDelTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbHotDelTitulo.setText("Eliminar Hotel");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Hotel"));
        jPanel1.setOpaque(false);

        lbHotDelHotelId.setText("Id del Hotel");

        txtHotDelHotelId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHotDelHotelIdActionPerformed(evt);
            }
        });

        btnHotDelBuscar.setText("Buscar");
        btnHotDelBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHotDelBuscarActionPerformed(evt);
            }
        });

        btnHotDelEliminar.setText("Eliminar");
        btnHotDelEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHotDelEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbHotDelHotelId)
                    .addComponent(txtHotDelHotelId)
                    .addComponent(btnHotDelBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHotDelEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbHotDelHotelId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHotDelHotelId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addComponent(btnHotDelBuscar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(btnHotDelEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Hotel a remover"));
        jPanel2.setOpaque(false);

        txtHotDelNombre.setEditable(false);
        txtHotDelNombre.setAutoscrolls(false);
        txtHotDelNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHotDelNombreActionPerformed(evt);
            }
        });

        txtHotDelDir.setEditable(false);

        txtHotDelCiudad.setEditable(false);

        txtHotDelTel.setEditable(false);

        txtHotDelAdmin.setEditable(false);

        lbHotDelNombre.setText("Nombre");

        lbHotDelDireccion.setText("Direccion");

        lbHotDelCiudad.setText("Ciudad");

        lbHotDelTelefono.setText("Telefono");

        lbHotDelAdmin.setText("Administrador");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbHotDelTelefono)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbHotDelAdmin, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbHotDelCiudad)
                            .addComponent(lbHotDelDireccion)
                            .addComponent(lbHotDelNombre))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtHotDelAdmin)
                            .addComponent(txtHotDelNombre)
                            .addComponent(txtHotDelDir)
                            .addComponent(txtHotDelCiudad)
                            .addComponent(txtHotDelTel, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHotDelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbHotDelNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHotDelDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbHotDelDireccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHotDelCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbHotDelCiudad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHotDelTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbHotDelTelefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHotDelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbHotDelAdmin))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout pnlHotDeleteLayout = new javax.swing.GroupLayout(pnlHotDelete);
        pnlHotDelete.setLayout(pnlHotDeleteLayout);
        pnlHotDeleteLayout.setHorizontalGroup(
            pnlHotDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHotDeleteLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(55, 55, 55)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
            .addGroup(pnlHotDeleteLayout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(lbHotDelTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHotDeleteLayout.setVerticalGroup(
            pnlHotDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHotDeleteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbHotDelTitulo)
                .addGap(10, 10, 10)
                .addGroup(pnlHotDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHotDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlHotDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnHotDelEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHotDelEliminarActionPerformed
        // TODO add your handling code here:
        //public Habitacion(int id, String descripcion, int precio, TipoHabitacion tipo);

        try {
            int id = Integer.parseInt(txtHotDelHotelId.getText());
            if (JOptionPane.showConfirmDialog(null,
                    "Esta seguro de eliminar el hotel con id " + id,
                    "Eliminar hotel", JOptionPane.OK_CANCEL_OPTION) == 0) {
                JOptionPane.showMessageDialog(null, service.deleteHotel(id), "Alerta", JOptionPane.INFORMATION_MESSAGE);
            }
            txtHotDelNombre.setText("");
            txtHotDelDir.setText("");
            txtHotDelCiudad.setText("");
            txtHotDelTel.setText("");
            txtHotDelAdmin.setText("");
            btnHotDelEliminar.setEnabled(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Datos invalidos");
        }

    }//GEN-LAST:event_btnHotDelEliminarActionPerformed

    private void txtHotDelNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHotDelNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHotDelNombreActionPerformed

    private void btnHotDelBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHotDelBuscarActionPerformed
        // TODO add your handling code here:

        try {
            int id = Integer.parseInt(txtHotDelHotelId.getText());

            for (Hotel hotel : hoteles) {
                if (hotel.getId() == id) {
                    txtHotDelNombre.setText(hotel.getNombre());
                    txtHotDelDir.setText(hotel.getDirecccion());
                    txtHotDelCiudad.setText(hotel.getCiudad());
                    txtHotDelTel.setText(hotel.getTelefono());
                    txtHotDelAdmin.setText(hotel.getAdministrador());
                    btnHotDelEliminar.setEnabled(true);
                    return;
                }
            }
            JOptionPane.showMessageDialog(null, "No se encontro el id " + id);
            txtHotDelNombre.setText("");
            txtHotDelDir.setText("");
            txtHotDelCiudad.setText("");
            txtHotDelTel.setText("");
            txtHotDelAdmin.setText("");
            btnHotDelEliminar.setEnabled(false);//*/

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Datos invalidos");
        }

    }//GEN-LAST:event_btnHotDelBuscarActionPerformed

    private void txtHotDelHotelIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHotDelHotelIdActionPerformed
        // TODO add your handling code here:
        btnHotDelEliminar.setEnabled(false);
    }//GEN-LAST:event_txtHotDelHotelIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHotDelBuscar;
    private javax.swing.JButton btnHotDelEliminar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbHotDelAdmin;
    private javax.swing.JLabel lbHotDelCiudad;
    private javax.swing.JLabel lbHotDelDireccion;
    private javax.swing.JLabel lbHotDelHotelId;
    private javax.swing.JLabel lbHotDelNombre;
    private javax.swing.JLabel lbHotDelTelefono;
    private javax.swing.JLabel lbHotDelTitulo;
    private javax.swing.JPanel pnlHotDelete;
    private javax.swing.JTextField txtHotDelAdmin;
    private javax.swing.JTextField txtHotDelCiudad;
    private javax.swing.JTextField txtHotDelDir;
    private javax.swing.JTextField txtHotDelHotelId;
    private javax.swing.JTextField txtHotDelNombre;
    private javax.swing.JTextField txtHotDelTel;
    // End of variables declaration//GEN-END:variables
}
