/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.mycompany.hotel.cliente.presentacion;

import co.mycompany.hotel.cliente.domain.services.HotelService;
import co.mycompany.hotel.commons.domain.Habitacion;
import co.mycompany.hotel.commons.domain.Hotel;
import co.mycompany.hotel.commons.domain.TipoHabitacion;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Jose Ricardo
 */
public class PnlHabModificar extends javax.swing.JPanel {

    private HotelService service;
    private TipoHabitacion tipos[];
    private ArrayList<Hotel> hoteles;
    private String usuario;
    private Habitacion habitacion;

    /**
     * Creates new form PnlAdmHabAdd
     */
    public PnlHabModificar(String usuario) {
        Habitacion habitacion = new Habitacion();
        this.usuario = usuario;
        service = new HotelService();
        this.service = service;
        hoteles = new ArrayList<>();
        initComponents();
        cargarValoresIniciales();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgAdmHabAdd = new javax.swing.JPanel();
        pnlHabModConsultar = new javax.swing.JPanel();
        lblIdHabitacion = new javax.swing.JLabel();
        btnBuscarId = new javax.swing.JButton();
        cbxHabModHoteles = new javax.swing.JComboBox<>();
        txtIdHabitacion = new javax.swing.JTextField();
        btnAdmHabModificar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbAdmHabDescripcion = new javax.swing.JLabel();
        txtAdmHabDescripcion = new javax.swing.JTextField();
        lbAdmHabPrecio = new javax.swing.JLabel();
        txtAdmHabPrecio = new javax.swing.JTextField();
        lbAdmHabTipo = new javax.swing.JLabel();
        cbxAdmHabTipo = new javax.swing.JComboBox<>();
        btnAdmHabFoto = new javax.swing.JButton();
        txtAdmHabFoto = new javax.swing.JTextField();
        lbHabMod = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(740, 235));

        bgAdmHabAdd.setPreferredSize(new java.awt.Dimension(570, 202));

        pnlHabModConsultar.setBorder(javax.swing.BorderFactory.createTitledBorder("Consular habitación"));
        pnlHabModConsultar.setOpaque(false);

        lblIdHabitacion.setText("Id");

        btnBuscarId.setText("Buscar");
        btnBuscarId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarIdActionPerformed(evt);
            }
        });

        cbxHabModHoteles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtIdHabitacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIdHabitacionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlHabModConsultarLayout = new javax.swing.GroupLayout(pnlHabModConsultar);
        pnlHabModConsultar.setLayout(pnlHabModConsultarLayout);
        pnlHabModConsultarLayout.setHorizontalGroup(
            pnlHabModConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHabModConsultarLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnBuscarId)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHabModConsultarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlHabModConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHabModConsultarLayout.createSequentialGroup()
                        .addComponent(lblIdHabitacion)
                        .addGap(18, 18, 18)
                        .addComponent(txtIdHabitacion))
                    .addComponent(cbxHabModHoteles, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        pnlHabModConsultarLayout.setVerticalGroup(
            pnlHabModConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHabModConsultarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlHabModConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdHabitacion)
                    .addComponent(txtIdHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxHabModHoteles, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(btnBuscarId)
                .addContainerGap())
        );

        lblIdHabitacion.getAccessibleContext().setAccessibleName("lblIdhotel");

        btnAdmHabModificar.setText("Modificar Habitacion");
        btnAdmHabModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmHabModificarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevos  datos"));
        jPanel1.setOpaque(false);

        lbAdmHabDescripcion.setText("Descripcion");

        lbAdmHabPrecio.setText("Precio");

        lbAdmHabTipo.setText("Tipo");

        cbxAdmHabTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAdmHabFoto.setText("Foto");
        btnAdmHabFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmHabFotoActionPerformed(evt);
            }
        });

        txtAdmHabFoto.setEnabled(false);
        txtAdmHabFoto.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAdmHabTipo)
                    .addComponent(lbAdmHabPrecio)
                    .addComponent(lbAdmHabDescripcion)
                    .addComponent(btnAdmHabFoto))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAdmHabDescripcion)
                    .addComponent(txtAdmHabPrecio)
                    .addComponent(cbxAdmHabTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAdmHabFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdmHabDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAdmHabDescripcion))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdmHabPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAdmHabPrecio))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxAdmHabTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAdmHabTipo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdmHabFoto)
                    .addComponent(txtAdmHabFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbHabMod.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbHabMod.setText("Modificar habitación");

        javax.swing.GroupLayout bgAdmHabAddLayout = new javax.swing.GroupLayout(bgAdmHabAdd);
        bgAdmHabAdd.setLayout(bgAdmHabAddLayout);
        bgAdmHabAddLayout.setHorizontalGroup(
            bgAdmHabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgAdmHabAddLayout.createSequentialGroup()
                .addGroup(bgAdmHabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgAdmHabAddLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(bgAdmHabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlHabModConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAdmHabModificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgAdmHabAddLayout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(lbHabMod)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        bgAdmHabAddLayout.setVerticalGroup(
            bgAdmHabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgAdmHabAddLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbHabMod)
                .addGap(18, 18, 18)
                .addGroup(bgAdmHabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bgAdmHabAddLayout.createSequentialGroup()
                        .addComponent(pnlHabModConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdmHabModificar)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgAdmHabAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgAdmHabAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdmHabModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmHabModificarActionPerformed
        // TODO add your handling code here:
//        public Habitacion(int id, String descripcion, int precio, TipoHabitacion tipo);
        TipoHabitacion tipo = this.tipos[cbxAdmHabTipo.getSelectedIndex()];
        String descripcion = txtAdmHabDescripcion.getText();
        int precio = Integer.parseInt(txtAdmHabPrecio.getText());
        int id = Integer.parseInt(txtIdHabitacion.getText());

        habitacion.setId(id);
        habitacion.setDescripcion(descripcion);
        habitacion.setPrecio(precio);
        habitacion.setTipo(tipo);
        habitacion.setFoto(txtAdmHabFoto.getText());
        JFrame jFrame = new JFrame();
        JOptionPane.showMessageDialog(jFrame, service.ModificarHabitacion(habitacion));
        txtAdmHabDescripcion.setText("");
        txtAdmHabPrecio.setText("");
        txtAdmHabFoto.setText("");

    }//GEN-LAST:event_btnAdmHabModificarActionPerformed

    private void btnAdmHabFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmHabFotoActionPerformed
        // TODO add your handling code here:

        JFileChooser j = new JFileChooser();
        FileNameExtensionFilter fil = new FileNameExtensionFilter("JPG, PNG & GIF", "jpg", "png", "gif");
        j.setFileFilter(fil);

        int s = j.showOpenDialog(this);
        if (s == JFileChooser.APPROVE_OPTION) {
            String ruta = j.getSelectedFile().getAbsolutePath();
            txtAdmHabFoto.setText(ruta);
        }
    }//GEN-LAST:event_btnAdmHabFotoActionPerformed

    private void btnBuscarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarIdActionPerformed
        try {
            int id = Integer.parseInt(txtIdHabitacion.getText());
            habitacion = service.getHabitacion(id);
            if (habitacion.getId_hotel() == hoteles.get(cbxHabModHoteles.getSelectedIndex()).getId()) {
                txtAdmHabDescripcion.setText(habitacion.getDescripcion());
                txtAdmHabPrecio.setText(String.valueOf(habitacion.getPrecio()));
                txtAdmHabFoto.setText(habitacion.getFoto());
                btnAdmHabModificar.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(null, "Habitacion no encontrada");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No es un id valido");
        }
    }//GEN-LAST:event_btnBuscarIdActionPerformed

    private void txtIdHabitacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIdHabitacionMouseClicked
        // TODO add your handling code here:
        btnAdmHabModificar.setEnabled(false);
        txtAdmHabDescripcion.setText("");
        txtAdmHabPrecio.setText("");
        txtAdmHabFoto.setText("");

    }//GEN-LAST:event_txtIdHabitacionMouseClicked

    private void cargarValoresIniciales() {
        btnAdmHabModificar.setEnabled(false);
        TipoHabitacion tipos[] = TipoHabitacion.values();
        this.tipos = tipos;
        cbxAdmHabTipo.removeAllItems();
        for (int i = 0; i < tipos.length; i++) {
            cbxAdmHabTipo.addItem(tipos[i].toString());
        }

        cbxHabModHoteles.addItem("Seleccione un hotel");
        String tipo = service.getSecionTipo(usuario);

        if (tipo.equals("Master")) {
            hoteles = service.getHotels("All_Hotels");
        } else {
            hoteles = service.getHotels(usuario);
        }
        cbxHabModHoteles.removeAllItems();
        if (hoteles != null) {
            for (int i = 0; i < hoteles.size(); i++) {
                cbxHabModHoteles.addItem(hoteles.get(i).getNombre());
            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgAdmHabAdd;
    private javax.swing.JButton btnAdmHabFoto;
    private javax.swing.JButton btnAdmHabModificar;
    private javax.swing.JButton btnBuscarId;
    private javax.swing.JComboBox<String> cbxAdmHabTipo;
    private javax.swing.JComboBox<String> cbxHabModHoteles;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbAdmHabDescripcion;
    private javax.swing.JLabel lbAdmHabPrecio;
    private javax.swing.JLabel lbAdmHabTipo;
    private javax.swing.JLabel lbHabMod;
    private javax.swing.JLabel lblIdHabitacion;
    private javax.swing.JPanel pnlHabModConsultar;
    private javax.swing.JTextField txtAdmHabDescripcion;
    private javax.swing.JTextField txtAdmHabFoto;
    private javax.swing.JTextField txtAdmHabPrecio;
    private javax.swing.JTextField txtIdHabitacion;
    // End of variables declaration//GEN-END:variables
}
