/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.mycompany.hotel.cliente.presentacion;

import co.mycompany.hotel.cliente.domain.services.HotelService;
import co.mycompany.hotel.commons.domain.Hotel;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Jose Ricardo
 */
public class PnlHotelUpdate extends javax.swing.JPanel {

    private HotelService service;
    private ArrayList<Hotel> hoteles;
    private String usuario;
    private boolean bandera;

    /**
     * Creates new form PnlAdmHabAdd
     */
    public PnlHotelUpdate(String usuario) {
        this.usuario = usuario;
        service = new HotelService();
        hoteles = new ArrayList<>();
        initComponents();
        bandera = false;
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgAdmHabAdd = new javax.swing.JPanel();
        lbAdmHotNombre = new javax.swing.JLabel();
        lbAdmHotDireccion = new javax.swing.JLabel();
        lbAdmHotCiudad = new javax.swing.JLabel();
        txtAdmHotUpNombre = new javax.swing.JTextField();
        txtAdmHotUpDir = new javax.swing.JTextField();
        lbAdmHotTelefono = new javax.swing.JLabel();
        btnAdmHotUpActualizar = new javax.swing.JButton();
        txtAdmHotUpFoto = new javax.swing.JTextField();
        btnAdmHabFoto = new javax.swing.JButton();
        txtAdmHotUpCiudad = new javax.swing.JTextField();
        txtAdmHotUpTel = new javax.swing.JTextField();
        cbxAdmHotUpHoteles = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtAdmHotUpAdmin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lbHotModTitulo = new javax.swing.JLabel();

        bgAdmHabAdd.setPreferredSize(new java.awt.Dimension(570, 202));

        lbAdmHotNombre.setText("Nombre");

        lbAdmHotDireccion.setText("Direccion");

        lbAdmHotCiudad.setText("Ciudad");

        txtAdmHotUpNombre.setAutoscrolls(false);

        lbAdmHotTelefono.setText("Telefono");

        btnAdmHotUpActualizar.setText("Actualizar");
        btnAdmHotUpActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmHotUpActualizarActionPerformed(evt);
            }
        });

        txtAdmHotUpFoto.setEnabled(false);
        txtAdmHotUpFoto.setFocusable(false);

        btnAdmHabFoto.setText("Foto");
        btnAdmHabFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmHabFotoActionPerformed(evt);
            }
        });

        cbxAdmHotUpHoteles.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxAdmHotUpHotelesItemStateChanged(evt);
            }
        });

        jLabel1.setText("Hotel");

        jLabel2.setText("Administrador");

        lbHotModTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbHotModTitulo.setText("Modificar Hotel");

        javax.swing.GroupLayout bgAdmHabAddLayout = new javax.swing.GroupLayout(bgAdmHabAdd);
        bgAdmHabAdd.setLayout(bgAdmHabAddLayout);
        bgAdmHabAddLayout.setHorizontalGroup(
            bgAdmHabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgAdmHabAddLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(bgAdmHabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbAdmHotCiudad)
                    .addComponent(lbAdmHotTelefono)
                    .addComponent(lbAdmHotDireccion)
                    .addComponent(lbAdmHotNombre)
                    .addComponent(btnAdmHabFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28)
                .addGroup(bgAdmHabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAdmHotUpAdmin)
                    .addComponent(txtAdmHotUpNombre)
                    .addComponent(txtAdmHotUpDir)
                    .addComponent(txtAdmHotUpCiudad)
                    .addComponent(txtAdmHotUpTel)
                    .addComponent(txtAdmHotUpFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(bgAdmHabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgAdmHabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnAdmHotUpActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbxAdmHotUpHoteles, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(71, 71, 71))
            .addGroup(bgAdmHabAddLayout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(lbHotModTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bgAdmHabAddLayout.setVerticalGroup(
            bgAdmHabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgAdmHabAddLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbHotModTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(bgAdmHabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdmHotUpNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAdmHotNombre)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgAdmHabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdmHotUpDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAdmHotDireccion)
                    .addComponent(cbxAdmHotUpHoteles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgAdmHabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAdmHotCiudad)
                    .addComponent(txtAdmHotUpCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(bgAdmHabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgAdmHabAddLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(bgAdmHabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbAdmHotTelefono)
                            .addComponent(txtAdmHotUpTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgAdmHabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdmHabFoto)
                            .addComponent(txtAdmHotUpFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bgAdmHabAddLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnAdmHotUpActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgAdmHabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdmHotUpAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgAdmHabAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(bgAdmHabAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdmHotUpActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmHotUpActualizarActionPerformed
        // TODO add your handling code here:
        //public Habitacion(int id, String descripcion, int precio, TipoHabitacion tipo);

        try {
            String nombre = txtAdmHotUpNombre.getText();
            String direccion = txtAdmHotUpDir.getText();
            String ciudad = txtAdmHotUpCiudad.getText();
            String telefono = txtAdmHotUpTel.getText();
            String admin = txtAdmHotUpAdmin.getText();
            Hotel hotel = new Hotel(cbxAdmHotUpHoteles.getSelectedIndex(), nombre, direccion, ciudad, telefono, admin);
            hotel.setFoto(txtAdmHotUpFoto.getText());
            JFrame jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, service.updateHotel(hotel, admin));
            txtAdmHotUpNombre.setText("");
            txtAdmHotUpDir.setText("");
            txtAdmHotUpCiudad.setText("");
            txtAdmHotUpTel.setText("");
            txtAdmHotUpFoto.setText("");
            txtAdmHotUpAdmin.setText("");
            cargarDatos();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Datos invalidos");
        }

    }//GEN-LAST:event_btnAdmHotUpActualizarActionPerformed

    private void btnAdmHabFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmHabFotoActionPerformed
        // TODO add your handling code here:

        JFileChooser j = new JFileChooser();
        FileNameExtensionFilter fil = new FileNameExtensionFilter("JPG, PNG & GIF", "jpg", "png", "gif");
        j.setFileFilter(fil);

        int s = j.showOpenDialog(this);
        if (s == JFileChooser.APPROVE_OPTION) {
            String ruta = j.getSelectedFile().getAbsolutePath();
            txtAdmHotUpFoto.setText(ruta);

        }

    }//GEN-LAST:event_btnAdmHabFotoActionPerformed

    private void cbxAdmHotUpHotelesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxAdmHotUpHotelesItemStateChanged
        // TODO add your handling code here:
        if (bandera) {
            try {
                int i = cbxAdmHotUpHoteles.getSelectedIndex()-1;
                txtAdmHotUpNombre.setText(hoteles.get(i).getNombre());
                txtAdmHotUpDir.setText(hoteles.get(i).getDirecccion());
                txtAdmHotUpCiudad.setText(hoteles.get(i).getCiudad());
                txtAdmHotUpTel.setText(hoteles.get(i).getTelefono());
                txtAdmHotUpFoto.setText(hoteles.get(i).getFoto());
                txtAdmHotUpAdmin.setText(hoteles.get(i).getAdministrador());
            } catch (Exception e) {
                txtAdmHotUpNombre.setText("");
                txtAdmHotUpDir.setText("");
                txtAdmHotUpCiudad.setText("");
                txtAdmHotUpTel.setText("");
                txtAdmHotUpFoto.setText("");
                txtAdmHotUpAdmin.setText("");
            }
        }
    }//GEN-LAST:event_cbxAdmHotUpHotelesItemStateChanged

    private void cargarDatos() {
        bandera = false;
        cbxAdmHotUpHoteles.removeAllItems();
        cbxAdmHotUpHoteles.addItem("Seleccione un hotel");
        hoteles.clear();
        try {

            hoteles.addAll(service.getHotels("All_Hotels"));
            if (hoteles != null) {
                hoteles.forEach(hotel -> cbxAdmHotUpHoteles.addItem(hotel.getNombre()));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No hay hoteles registrados");

        }
        bandera = true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgAdmHabAdd;
    private javax.swing.JButton btnAdmHabFoto;
    private javax.swing.JButton btnAdmHotUpActualizar;
    private javax.swing.JComboBox<String> cbxAdmHotUpHoteles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbAdmHotCiudad;
    private javax.swing.JLabel lbAdmHotDireccion;
    private javax.swing.JLabel lbAdmHotNombre;
    private javax.swing.JLabel lbAdmHotTelefono;
    private javax.swing.JLabel lbHotModTitulo;
    private javax.swing.JTextField txtAdmHotUpAdmin;
    private javax.swing.JTextField txtAdmHotUpCiudad;
    private javax.swing.JTextField txtAdmHotUpDir;
    private javax.swing.JTextField txtAdmHotUpFoto;
    private javax.swing.JTextField txtAdmHotUpNombre;
    private javax.swing.JTextField txtAdmHotUpTel;
    // End of variables declaration//GEN-END:variables
}
