/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.mycompany.hotel.cliente.presentacion;

import co.mycompany.hotel.cliente.domain.services.UserService;

/**
 *
 * @author Jose Ricardo
 */
public class PnlLogin extends javax.swing.JPanel {

    private FrmMain panel;
    private javax.swing.JPanel aux;

    /**
     * Creates new form PnlLogin
     */
    public PnlLogin(FrmMain panel) {
        this.panel = panel;
        aux = new javax.swing.JPanel();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLogLogin = new javax.swing.JPanel();
        btnLogRegistrarse = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbLogTitulo = new javax.swing.JLabel();
        lbLogUsuario = new javax.swing.JLabel();
        txtLogUsuario = new javax.swing.JTextField();
        lbLogPassword = new javax.swing.JLabel();
        txtLogPassword = new javax.swing.JPasswordField();
        btnLogIniciar = new javax.swing.JButton();

        pnlLogLogin.setPreferredSize(new java.awt.Dimension(700, 300));

        btnLogRegistrarse.setText("Registrarse");
        btnLogRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogRegistrarseActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbLogTitulo.setText("Iniciar Seccion");

        lbLogUsuario.setText("Usuario");

        lbLogPassword.setText("Contraseña");

        btnLogIniciar.setText("Iniciar");
        btnLogIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogIniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbLogPassword)
                    .addComponent(lbLogUsuario))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnLogIniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtLogUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLogPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lbLogTitulo)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lbLogTitulo)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLogUsuario)
                    .addComponent(txtLogUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLogPassword)
                    .addComponent(txtLogPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnLogIniciar)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlLogLoginLayout = new javax.swing.GroupLayout(pnlLogLogin);
        pnlLogLogin.setLayout(pnlLogLoginLayout);
        pnlLogLoginLayout.setHorizontalGroup(
            pnlLogLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogLoginLayout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
            .addGroup(pnlLogLoginLayout.createSequentialGroup()
                .addGap(304, 304, 304)
                .addComponent(btnLogRegistrarse)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLogLoginLayout.setVerticalGroup(
            pnlLogLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogLoginLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnLogRegistrarse)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlLogLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlLogLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogIniciarActionPerformed
        // TODO add your handling code here:
        String tipo = "";
        String usuario = txtLogUsuario.getText();
        String password = txtLogPassword.getText();
        if(!usuario.equals("All_Hotels")){
            tipo = UserService.autenticacion(usuario, password);
        }
        switch (tipo) {
            case "Master":
                panel.cargarUsuario(usuario);
                panel.cargarAdmMaster();
                break;
            case "Junior":
                panel.cargarUsuario(usuario);
                panel.cargarAdmJunior();
                break;
            case "Cliente":
                panel.cargarUsuario(usuario);
                panel.cargarCliente();
                break;
            default:
                panel.cargarLogin();
        }

    }//GEN-LAST:event_btnLogIniciarActionPerformed

    private void btnLogRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogRegistrarseActionPerformed
        // TODO add your handling code here:
           panel.cargarRegistrar("Cliente");   
    }//GEN-LAST:event_btnLogRegistrarseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogIniciar;
    private javax.swing.JButton btnLogRegistrarse;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbLogPassword;
    private javax.swing.JLabel lbLogTitulo;
    private javax.swing.JLabel lbLogUsuario;
    private javax.swing.JPanel pnlLogLogin;
    private javax.swing.JPasswordField txtLogPassword;
    private javax.swing.JTextField txtLogUsuario;
    // End of variables declaration//GEN-END:variables
}
