/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.mycompany.hotel.cliente.presentacion;

/**
 *
 * @author Jose Ricardo
 */
public class PnlPerPassword extends javax.swing.JPanel {

    /**
     * Creates new form PnlPerPassword
     */
    public PnlPerPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPerPassword = new javax.swing.JPanel();
        lbPerPasTitulo = new javax.swing.JLabel();

        lbPerPasTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbPerPasTitulo.setText("Cambiar Contraseña");

        javax.swing.GroupLayout pnlPerPasswordLayout = new javax.swing.GroupLayout(pnlPerPassword);
        pnlPerPassword.setLayout(pnlPerPasswordLayout);
        pnlPerPasswordLayout.setHorizontalGroup(
            pnlPerPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPerPasswordLayout.createSequentialGroup()
                .addContainerGap(308, Short.MAX_VALUE)
                .addComponent(lbPerPasTitulo)
                .addGap(291, 291, 291))
        );
        pnlPerPasswordLayout.setVerticalGroup(
            pnlPerPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPerPasswordLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lbPerPasTitulo)
                .addContainerGap(256, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPerPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPerPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbPerPasTitulo;
    private javax.swing.JPanel pnlPerPassword;
    // End of variables declaration//GEN-END:variables
}
