/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.mycompany.hotel.cliente.presentacion;

import co.mycompany.hotel.cliente.domain.services.HotelService;
import co.mycompany.hotel.commons.domain.Persona;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose Ricardo
 */
public class PnlPerEliminar extends javax.swing.JPanel {

    private HotelService service;
    private String tipo;
    private int idUsuario;


    /**
     * Creates new form PnlAdmHabAdd
     */
    public PnlPerEliminar() {
        service = new HotelService();
        initComponents();
        btnPerEliEliminar.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPerEliminar = new javax.swing.JPanel();
        lbPerEliNombre = new javax.swing.JLabel();
        txtPerEliNombre = new javax.swing.JTextField();
        txtPerEliDir = new javax.swing.JTextField();
        txtPerEliTel = new javax.swing.JTextField();
        lbPerEliDireccion = new javax.swing.JLabel();
        lbPerEliTelefono = new javax.swing.JLabel();
        lbPerEliUser1 = new javax.swing.JLabel();
        txtPerEliTipo = new javax.swing.JTextField();
        lbPerEliId = new javax.swing.JLabel();
        txtPerEliId = new javax.swing.JTextField();
        btnPerEliEliminar = new javax.swing.JButton();
        lbPerEliTitulo = new javax.swing.JLabel();
        btnPerEliBuscar = new javax.swing.JButton();
        txtPerEliUser = new javax.swing.JTextField();
        lbPerEliUser = new javax.swing.JLabel();

        setOpaque(false);

        pnlPerEliminar.setOpaque(false);
        pnlPerEliminar.setPreferredSize(new java.awt.Dimension(570, 202));

        lbPerEliNombre.setText("Nombre");

        txtPerEliNombre.setEditable(false);

        txtPerEliDir.setEditable(false);

        txtPerEliTel.setEditable(false);

        lbPerEliDireccion.setText("Direccion");

        lbPerEliTelefono.setText("Telefono");

        lbPerEliUser1.setText("Tipo Usuario");

        txtPerEliTipo.setEditable(false);

        lbPerEliId.setText("Numero cedula");

        txtPerEliId.setEditable(false);

        javax.swing.GroupLayout pnlPerEliminarLayout = new javax.swing.GroupLayout(pnlPerEliminar);
        pnlPerEliminar.setLayout(pnlPerEliminarLayout);
        pnlPerEliminarLayout.setHorizontalGroup(
            pnlPerEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPerEliminarLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(pnlPerEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlPerEliminarLayout.createSequentialGroup()
                        .addComponent(lbPerEliUser1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPerEliTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPerEliminarLayout.createSequentialGroup()
                        .addGroup(pnlPerEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPerEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pnlPerEliminarLayout.createSequentialGroup()
                                    .addComponent(lbPerEliNombre)
                                    .addGap(102, 102, 102))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPerEliminarLayout.createSequentialGroup()
                                    .addGroup(pnlPerEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lbPerEliTelefono, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbPerEliDireccion, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(pnlPerEliminarLayout.createSequentialGroup()
                                .addComponent(lbPerEliId)
                                .addGap(68, 68, 68)))
                        .addGroup(pnlPerEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPerEliId, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlPerEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPerEliNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPerEliDir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPerEliTel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(42, 42, 42))
        );
        pnlPerEliminarLayout.setVerticalGroup(
            pnlPerEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPerEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPerEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPerEliNombre)
                    .addComponent(txtPerEliNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPerEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPerEliId)
                    .addComponent(txtPerEliId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPerEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPerEliDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPerEliDireccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPerEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPerEliTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPerEliTelefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPerEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPerEliTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPerEliUser1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnPerEliEliminar.setText("Eliminar Usuario");
        btnPerEliEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerEliEliminarActionPerformed(evt);
            }
        });

        lbPerEliTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbPerEliTitulo.setText("Eliminar Usuario");

        btnPerEliBuscar.setText("Buscar");
        btnPerEliBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerEliBuscarActionPerformed(evt);
            }
        });

        txtPerEliUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPerEliUserActionPerformed(evt);
            }
        });

        lbPerEliUser.setText("Usuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(lbPerEliTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(pnlPerEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPerEliEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPerEliBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPerEliUser)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(lbPerEliUser)))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPerEliTitulo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lbPerEliUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPerEliUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPerEliBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(btnPerEliEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(pnlPerEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPerEliEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerEliEliminarActionPerformed
        // TODO add your handling code here:
        //public Habitacion(int id, String descripcion, int precio, TipoHabitacion tipo);

        try {
            if (JOptionPane.showConfirmDialog(null,
                    "Esta seguro de eliminar el usuario con id " + idUsuario,
                    "Eliminar hotel", JOptionPane.OK_CANCEL_OPTION) == 0) {
                JOptionPane.showMessageDialog(null, service.deletePersona(idUsuario, tipo), "Alerta", JOptionPane.INFORMATION_MESSAGE);
            }
            txtPerEliDir.setText("");
            txtPerEliId.setText("");
            txtPerEliNombre.setText("");
            txtPerEliTel.setText("");
            txtPerEliTipo.setText("");
            btnPerEliEliminar.setEnabled(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se pudo conectar con el servidor");
        }

    }//GEN-LAST:event_btnPerEliEliminarActionPerformed

    private void btnPerEliBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerEliBuscarActionPerformed
        // TODO add your handling code here:
        String usuario = txtPerEliUser.getText();
        try {
            Persona persona = service.getPersona(usuario);
            if (persona.getId() != 0) {
                txtPerEliDir.setText(persona.getDireccion());
                txtPerEliId.setText("" + persona.getId());
                this.idUsuario = persona.getId();
                txtPerEliNombre.setText(persona.getNombre());
                txtPerEliTel.setText(persona.getTelefono());
                this.tipo = service.getSecionTipo(usuario);
                txtPerEliTipo.setText(this.tipo);
                btnPerEliEliminar.setEnabled(true);
            }
            else{
                JOptionPane.showMessageDialog(null, "No se encontró el usuario");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en la conexion");
        }

    }//GEN-LAST:event_btnPerEliBuscarActionPerformed

    private void txtPerEliUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPerEliUserActionPerformed
        // TODO add your handling code here:
        btnPerEliEliminar.setEnabled(false);
    }//GEN-LAST:event_txtPerEliUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPerEliBuscar;
    private javax.swing.JButton btnPerEliEliminar;
    private javax.swing.JLabel lbPerEliDireccion;
    private javax.swing.JLabel lbPerEliId;
    private javax.swing.JLabel lbPerEliNombre;
    private javax.swing.JLabel lbPerEliTelefono;
    private javax.swing.JLabel lbPerEliTitulo;
    private javax.swing.JLabel lbPerEliUser;
    private javax.swing.JLabel lbPerEliUser1;
    private javax.swing.JPanel pnlPerEliminar;
    private javax.swing.JTextField txtPerEliDir;
    private javax.swing.JTextField txtPerEliId;
    private javax.swing.JTextField txtPerEliNombre;
    private javax.swing.JTextField txtPerEliTel;
    private javax.swing.JTextField txtPerEliTipo;
    private javax.swing.JTextField txtPerEliUser;
    // End of variables declaration//GEN-END:variables
}
