/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.mycompany.hotel.cliente.presentacion;

import co.mycompany.hotel.cliente.domain.services.HotelService;
import co.mycompany.hotel.commons.domain.Persona;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose Ricardo
 */
public class PnlPerPerfil extends javax.swing.JPanel {

    private HotelService service;
    private String usuario;

    /**
     * Creates new form PnlAdmHabAdd
     */
    public PnlPerPerfil(String usuario) {
        service = new HotelService();
        this.usuario = usuario;
        initComponents();
        cargarDatos();

    }

    private void cargarDatos() {
        try {
            Persona persona = service.getPersona(usuario);
            System.out.println( persona.toString());
            if (persona != null) {
                txtPerPerUser.setText(usuario);
                txtPerPersDir.setText(persona.getDireccion());
                txtPerPersId.setText(""+persona.getId());
                txtPerPersNombre.setText(persona.getNombre());
                txtPerPersTel.setText(persona.getTelefono());
                System.out.println(persona.getClave());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en la conexion");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgAdmHabAdd = new javax.swing.JPanel();
        lbAdmPersDireccion = new javax.swing.JLabel();
        lbAdmPersTelefono = new javax.swing.JLabel();
        lbAdmPersId = new javax.swing.JLabel();
        txtPerPersId = new javax.swing.JTextField();
        txtPerPersTel = new javax.swing.JTextField();
        txtPerPersNombre = new javax.swing.JTextField();
        txtPerPersDir = new javax.swing.JTextField();
        lbAdmPersNombre = new javax.swing.JLabel();
        txtPerPerUser = new javax.swing.JTextField();
        lbAdmPersUser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        bgAdmHabAdd.setPreferredSize(new java.awt.Dimension(570, 202));

        lbAdmPersDireccion.setText("Direccion");

        lbAdmPersTelefono.setText("Telefono");

        lbAdmPersId.setText("Numero cedula");

        txtPerPersId.setEditable(false);

        txtPerPersTel.setEditable(false);

        txtPerPersNombre.setEditable(false);

        txtPerPersDir.setEditable(false);

        lbAdmPersNombre.setText("Nombre");

        txtPerPerUser.setEditable(false);

        lbAdmPersUser.setText("Usuario");

        javax.swing.GroupLayout bgAdmHabAddLayout = new javax.swing.GroupLayout(bgAdmHabAdd);
        bgAdmHabAdd.setLayout(bgAdmHabAddLayout);
        bgAdmHabAddLayout.setHorizontalGroup(
            bgAdmHabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgAdmHabAddLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(bgAdmHabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(bgAdmHabAddLayout.createSequentialGroup()
                        .addComponent(lbAdmPersUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPerPerUser, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgAdmHabAddLayout.createSequentialGroup()
                        .addGroup(bgAdmHabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbAdmPersId)
                            .addComponent(lbAdmPersNombre)
                            .addComponent(lbAdmPersDireccion)
                            .addComponent(lbAdmPersTelefono))
                        .addGap(68, 68, 68)
                        .addGroup(bgAdmHabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPerPersNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPerPersId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPerPersDir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPerPersTel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(46, 46, 46))
        );
        bgAdmHabAddLayout.setVerticalGroup(
            bgAdmHabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgAdmHabAddLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(bgAdmHabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPerPerUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAdmPersUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgAdmHabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAdmPersId)
                    .addComponent(txtPerPersId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgAdmHabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPerPersNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAdmPersNombre, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(6, 6, 6)
                .addGroup(bgAdmHabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPerPersDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAdmPersDireccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgAdmHabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPerPersTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAdmPersTelefono))
                .addGap(24, 24, 24))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Datos de Usuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(325, 325, 325)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(198, Short.MAX_VALUE)
                .addComponent(bgAdmHabAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bgAdmHabAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgAdmHabAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbAdmPersDireccion;
    private javax.swing.JLabel lbAdmPersId;
    private javax.swing.JLabel lbAdmPersNombre;
    private javax.swing.JLabel lbAdmPersTelefono;
    private javax.swing.JLabel lbAdmPersUser;
    private javax.swing.JTextField txtPerPerUser;
    private javax.swing.JTextField txtPerPersDir;
    private javax.swing.JTextField txtPerPersId;
    private javax.swing.JTextField txtPerPersNombre;
    private javax.swing.JTextField txtPerPersTel;
    // End of variables declaration//GEN-END:variables
}
