/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.mycompany.hotel.cliente.presentacion;

import co.mycompany.hotel.cliente.domain.services.HotelService;
import co.mycompany.hotel.commons.domain.Persona;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose Ricardo
 */
public class PnlPerPassword extends javax.swing.JPanel {

    private HotelService service;
    private String usuario;
    private String tipo;

    /**
     * Creates new form PnlPerPassword
     */
    public PnlPerPassword(String usuario, String tipo) {
        service = new HotelService();
        this.usuario = usuario;
        this.tipo = tipo;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPerPassword = new javax.swing.JPanel();
        lbPerPasTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbPerModPassword = new javax.swing.JLabel();
        lbPerModNueva = new javax.swing.JLabel();
        lbPerModRepetir = new javax.swing.JLabel();
        txtPerModPassword = new javax.swing.JPasswordField();
        txtPerModNueva = new javax.swing.JPasswordField();
        txtPerModRepetir = new javax.swing.JPasswordField();
        btnPerModCambiar = new javax.swing.JButton();

        setOpaque(false);

        pnlPerPassword.setOpaque(false);

        lbPerPasTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbPerPasTitulo.setText("Cambiar Contraseña");

        jPanel1.setOpaque(false);

        lbPerModPassword.setText("Contraseña Actual");

        lbPerModNueva.setText("Nueva Contraseña");

        lbPerModRepetir.setText("Repita nueva Contraseña");

        btnPerModCambiar.setText("Cambiar Contraseña");
        btnPerModCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerModCambiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPerModNueva)
                    .addComponent(lbPerModPassword)
                    .addComponent(lbPerModRepetir))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtPerModNueva, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(txtPerModRepetir, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPerModPassword))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addComponent(btnPerModCambiar)
                .addGap(127, 127, 127))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPerModPassword)
                    .addComponent(txtPerModPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPerModNueva)
                    .addComponent(txtPerModNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPerModRepetir)
                    .addComponent(txtPerModRepetir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnPerModCambiar)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlPerPasswordLayout = new javax.swing.GroupLayout(pnlPerPassword);
        pnlPerPassword.setLayout(pnlPerPasswordLayout);
        pnlPerPasswordLayout.setHorizontalGroup(
            pnlPerPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPerPasswordLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbPerPasTitulo)
                .addGap(291, 291, 291))
            .addGroup(pnlPerPasswordLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );
        pnlPerPasswordLayout.setVerticalGroup(
            pnlPerPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPerPasswordLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lbPerPasTitulo)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPerPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPerPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPerModCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerModCambiarActionPerformed
        // TODO add your handling code here:
        if (txtPerModNueva.getText().equals(txtPerModRepetir.getText())) {
            Persona persona = service.getPersona(usuario);
            if(txtPerModPassword.getText().equals(persona.getClave())){
                persona.setUsuario(usuario);
                persona.setClave(txtPerModNueva.getText());
                JOptionPane.showMessageDialog(null, service.updatePersona(persona, tipo));

            }
            else{
                JOptionPane.showMessageDialog(null, "Contraseña equivocada");
                txtPerModPassword.setText("");
            }     
        }
        else{
            JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden");
            txtPerModNueva.setText("");
            txtPerModRepetir.setText("");
        }

    }//GEN-LAST:event_btnPerModCambiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPerModCambiar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbPerModNueva;
    private javax.swing.JLabel lbPerModPassword;
    private javax.swing.JLabel lbPerModRepetir;
    private javax.swing.JLabel lbPerPasTitulo;
    private javax.swing.JPanel pnlPerPassword;
    private javax.swing.JPasswordField txtPerModNueva;
    private javax.swing.JPasswordField txtPerModPassword;
    private javax.swing.JPasswordField txtPerModRepetir;
    // End of variables declaration//GEN-END:variables
}
