/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.mycompany.hotel.cliente.presentacion;

import co.mycompany.hotel.cliente.domain.services.HotelService;
import co.mycompany.hotel.commons.domain.Persona;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose Ricardo
 */
public class PnlPerModificar extends javax.swing.JPanel {

    private HotelService service;
    private String usuario;
    private String tipo;
    private Persona persona;

    /**
     * Creates new form PnlAdmHabAdd
     */
    public PnlPerModificar(String usuario,String tipo) {
        service = new HotelService();
        this.usuario = usuario;
        this.tipo = tipo;
        initComponents();
        cargarDatos();
        persona = new Persona();
        

    }

    private void cargarDatos() {
        try { 
            persona = service.getPersona(usuario);
            if (persona != null) {
                txtPerModUser.setText(usuario);
                txtPerModDir.setText(persona.getDireccion());
                txtPerModId.setText(""+persona.getId());
                txtPerModNombre.setText(persona.getNombre());
                txtPerModTel.setText(persona.getTelefono());
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en la conexion");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPerModificar = new javax.swing.JPanel();
        lbPerModDireccion = new javax.swing.JLabel();
        lbPerModTelefono = new javax.swing.JLabel();
        lbPerModId = new javax.swing.JLabel();
        txtPerModId = new javax.swing.JTextField();
        txtPerModTel = new javax.swing.JTextField();
        txtPerModNombre = new javax.swing.JTextField();
        txtPerModDir = new javax.swing.JTextField();
        lbPerModNombre = new javax.swing.JLabel();
        txtPerModUser = new javax.swing.JTextField();
        lbPerModUser = new javax.swing.JLabel();
        lbPerModTitulo = new javax.swing.JLabel();
        btnPerModActualizar = new javax.swing.JButton();

        pnlPerModificar.setPreferredSize(new java.awt.Dimension(570, 202));

        lbPerModDireccion.setText("Direccion");

        lbPerModTelefono.setText("Telefono");

        lbPerModId.setText("Numero cedula");

        txtPerModId.setEditable(false);

        lbPerModNombre.setText("Nombre");

        txtPerModUser.setEditable(false);

        lbPerModUser.setText("Usuario");

        javax.swing.GroupLayout pnlPerModificarLayout = new javax.swing.GroupLayout(pnlPerModificar);
        pnlPerModificar.setLayout(pnlPerModificarLayout);
        pnlPerModificarLayout.setHorizontalGroup(
            pnlPerModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPerModificarLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(pnlPerModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlPerModificarLayout.createSequentialGroup()
                        .addComponent(lbPerModUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPerModUser, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPerModificarLayout.createSequentialGroup()
                        .addGroup(pnlPerModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPerModId)
                            .addComponent(lbPerModNombre)
                            .addComponent(lbPerModDireccion)
                            .addComponent(lbPerModTelefono))
                        .addGap(68, 68, 68)
                        .addGroup(pnlPerModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPerModNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPerModId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPerModDir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPerModTel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(46, 46, 46))
        );
        pnlPerModificarLayout.setVerticalGroup(
            pnlPerModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPerModificarLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(pnlPerModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPerModUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPerModUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPerModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPerModId)
                    .addComponent(txtPerModId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPerModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPerModNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPerModNombre, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(6, 6, 6)
                .addGroup(pnlPerModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPerModDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPerModDireccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPerModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPerModTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPerModTelefono))
                .addGap(24, 24, 24))
        );

        lbPerModTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbPerModTitulo.setText("Actualizar Usuario");

        btnPerModActualizar.setText("Actualizar");
        btnPerModActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerModActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(lbPerModTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(pnlPerModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnPerModActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPerModTitulo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlPerModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btnPerModActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPerModActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerModActualizarActionPerformed
        // TODO add your handling code here:
        persona.setUsuario(usuario);
        persona.setDireccion(txtPerModDir.getText());
        persona.setNombre(txtPerModNombre.getText());
        persona.setTelefono(txtPerModTel.getText());
        try{
        JOptionPane.showMessageDialog(null, service.updatePersona(persona, tipo));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error en la conexion");
        }
    }//GEN-LAST:event_btnPerModActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPerModActualizar;
    private javax.swing.JLabel lbPerModDireccion;
    private javax.swing.JLabel lbPerModId;
    private javax.swing.JLabel lbPerModNombre;
    private javax.swing.JLabel lbPerModTelefono;
    private javax.swing.JLabel lbPerModTitulo;
    private javax.swing.JLabel lbPerModUser;
    private javax.swing.JPanel pnlPerModificar;
    private javax.swing.JTextField txtPerModDir;
    private javax.swing.JTextField txtPerModId;
    private javax.swing.JTextField txtPerModNombre;
    private javax.swing.JTextField txtPerModTel;
    private javax.swing.JTextField txtPerModUser;
    // End of variables declaration//GEN-END:variables
}
