/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.mycompany.hotel.cliente.presentacion;

import co.mycompany.hotel.cliente.domain.services.HotelService;
import co.mycompany.hotel.commons.domain.Hotel;
import co.mycompany.hotel.commons.domain.Reserva;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose Ricardo
 */
public class PnlResEliminar extends javax.swing.JPanel {

    private HotelService service;
    private String usuario;
    private ArrayList<Reserva> reservas;
    private Reserva actReserva;

    /**
     * Creates new form pnlResUpdate
     */
    public PnlResEliminar(String usuario) {
        service = new HotelService();
        this.usuario = usuario;
        this.reservas = new ArrayList<>();
        initComponents();
        btnResUpActualizar.setEnabled(false);
        btnResUpBuscar.setEnabled(false);
        cargarReservas();
    }

    private void cargarReservas() {
        try {
            ArrayList<Hotel> hoteles = service.getHotels(usuario);
            if (hoteles != null) {
                for (Hotel hotel : hoteles) {
                    reservas.addAll(service.getReservaHotel(hotel.getId()));
                }
                btnResUpBuscar.setEnabled(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en la conexion");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlResEliminar = new javax.swing.JPanel();
        pnlResEliEliminar = new javax.swing.JPanel();
        txtResEliIdUsuario = new javax.swing.JTextField();
        txtResEliIdHotel = new javax.swing.JTextField();
        txtResEliIdHabitacion = new javax.swing.JTextField();
        jdcResEliFechaIni = new com.toedter.calendar.JDateChooser();
        jdcResEliFechaFin = new com.toedter.calendar.JDateChooser();
        lbResEliIdUsuario = new javax.swing.JLabel();
        lbResEliIdHotel = new javax.swing.JLabel();
        lbResEliIdHabitacion = new javax.swing.JLabel();
        lbResEliFechaIni = new javax.swing.JLabel();
        lbResEliFechaFin = new javax.swing.JLabel();
        pnlResUpActualizar = new javax.swing.JPanel();
        txtResUpIdReserva = new javax.swing.JTextField();
        lbResUpIdReserva = new javax.swing.JLabel();
        btnResUpBuscar = new javax.swing.JButton();
        btnResUpActualizar = new javax.swing.JButton();
        lbResEliTitulo = new javax.swing.JLabel();

        pnlResEliEliminar.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de la reserva"));

        txtResEliIdUsuario.setEditable(false);

        txtResEliIdHotel.setEditable(false);

        lbResEliIdUsuario.setText("id Usuario");

        lbResEliIdHotel.setText("id Hotel");

        lbResEliIdHabitacion.setText("id Habitacion");

        lbResEliFechaIni.setText("Fecha Inicio");

        lbResEliFechaFin.setText("Fecha Fin");

        javax.swing.GroupLayout pnlResEliEliminarLayout = new javax.swing.GroupLayout(pnlResEliEliminar);
        pnlResEliEliminar.setLayout(pnlResEliEliminarLayout);
        pnlResEliEliminarLayout.setHorizontalGroup(
            pnlResEliEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlResEliEliminarLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(pnlResEliEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbResEliIdUsuario)
                    .addComponent(lbResEliIdHotel)
                    .addComponent(lbResEliIdHabitacion)
                    .addComponent(lbResEliFechaIni)
                    .addComponent(lbResEliFechaFin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(pnlResEliEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtResEliIdUsuario)
                    .addComponent(txtResEliIdHotel)
                    .addComponent(txtResEliIdHabitacion)
                    .addComponent(jdcResEliFechaIni, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(jdcResEliFechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );
        pnlResEliEliminarLayout.setVerticalGroup(
            pnlResEliEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResEliEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlResEliEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlResEliEliminarLayout.createSequentialGroup()
                        .addGroup(pnlResEliEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtResEliIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbResEliIdUsuario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlResEliEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtResEliIdHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbResEliIdHotel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlResEliEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtResEliIdHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbResEliIdHabitacion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdcResEliFechaIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbResEliFechaIni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlResEliEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jdcResEliFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbResEliFechaFin))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlResUpActualizar.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar y actualizar reserva"));

        txtResUpIdReserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtResUpIdReservaMouseClicked(evt);
            }
        });
        txtResUpIdReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResUpIdReservaActionPerformed(evt);
            }
        });

        lbResUpIdReserva.setText("id Reserva");

        btnResUpBuscar.setText("Buscar");
        btnResUpBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResUpBuscarActionPerformed(evt);
            }
        });

        btnResUpActualizar.setText("Actualizar");
        btnResUpActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResUpActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlResUpActualizarLayout = new javax.swing.GroupLayout(pnlResUpActualizar);
        pnlResUpActualizar.setLayout(pnlResUpActualizarLayout);
        pnlResUpActualizarLayout.setHorizontalGroup(
            pnlResUpActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlResUpActualizarLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(lbResUpIdReserva)
                .addGap(18, 18, 18)
                .addComponent(txtResUpIdReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(pnlResUpActualizarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlResUpActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnResUpActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(btnResUpBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlResUpActualizarLayout.setVerticalGroup(
            pnlResUpActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResUpActualizarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlResUpActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtResUpIdReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbResUpIdReserva))
                .addGap(23, 23, 23)
                .addComponent(btnResUpBuscar)
                .addGap(18, 18, 18)
                .addComponent(btnResUpActualizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbResEliTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbResEliTitulo.setText("Eliminar Reserva");

        javax.swing.GroupLayout pnlResEliminarLayout = new javax.swing.GroupLayout(pnlResEliminar);
        pnlResEliminar.setLayout(pnlResEliminarLayout);
        pnlResEliminarLayout.setHorizontalGroup(
            pnlResEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResEliminarLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(pnlResUpActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(pnlResEliEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(pnlResEliminarLayout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addComponent(lbResEliTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlResEliminarLayout.setVerticalGroup(
            pnlResEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResEliminarLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lbResEliTitulo)
                .addGap(27, 27, 27)
                .addGroup(pnlResEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlResUpActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlResEliEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlResEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlResEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnResUpActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResUpActualizarActionPerformed
        // TODO add your handling code here:
        try {
            SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String formattedDate = simpleDateFormat.format(jdcResEliFechaIni.getDate());
            Date fechaIni = Date.valueOf(formattedDate);
            formattedDate = simpleDateFormat.format(jdcResEliFechaFin.getDate());
            Date fechaFin = Date.valueOf(formattedDate);
            actReserva.setId_habitacion(Integer.parseInt(txtResEliIdHabitacion.getText()));
            actReserva.setFechaInicio(fechaIni);
            actReserva.setFechaFin(fechaFin);
            if (JOptionPane.showConfirmDialog(null,
                    "Esta seguro de modificar la reserva con id " + actReserva.getId() + "? Esta opción debe acordada con Cliente",
                    "Modificar Reserva", JOptionPane.OK_CANCEL_OPTION) == 0) {
                //JOptionPane.showMessageDialog(null, service.updateReserva(actReserva), "Alerta", JOptionPane.INFORMATION_MESSAGE);
                actReserva = null;
                txtResEliIdHabitacion.setText("");
                txtResEliIdHotel.setText("");
                txtResEliIdUsuario.setText("");
                jdcResEliFechaFin.setDate(null);
                jdcResEliFechaIni.setDate(null);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Datos invalidos");
        }
    }//GEN-LAST:event_btnResUpActualizarActionPerformed

    private void btnResUpBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResUpBuscarActionPerformed
        // TODO add your handling code here:
        if (reservas != null) {
            try {
                int id = Integer.parseInt(txtResUpIdReserva.getText());
                for (Reserva reserva : reservas) {
                    if (reserva.getId() == id) {
                        actReserva = reserva;
                        txtResEliIdHabitacion.setText("" + actReserva.getId_habitacion());
                        txtResEliIdHotel.setText("" + actReserva.getId_hotel());
                        txtResEliIdUsuario.setText("" + actReserva.getId_persona());
                        jdcResEliFechaFin.setDate(actReserva.getFechaFin());
                        jdcResEliFechaIni.setDate(actReserva.getFechaInicio());
                        btnResUpActualizar.setEnabled(true);
                        return;
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Id invalida");
            }
        }
    }//GEN-LAST:event_btnResUpBuscarActionPerformed

    private void txtResUpIdReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResUpIdReservaActionPerformed
        // TODO add your handling code here:
        btnResUpActualizar.setEnabled(false);
    }//GEN-LAST:event_txtResUpIdReservaActionPerformed

    private void txtResUpIdReservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtResUpIdReservaMouseClicked
        // TODO add your handling code here:
        btnResUpActualizar.setEnabled(false);
    }//GEN-LAST:event_txtResUpIdReservaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnResUpActualizar;
    private javax.swing.JButton btnResUpBuscar;
    private com.toedter.calendar.JDateChooser jdcResEliFechaFin;
    private com.toedter.calendar.JDateChooser jdcResEliFechaIni;
    private javax.swing.JLabel lbResEliFechaFin;
    private javax.swing.JLabel lbResEliFechaIni;
    private javax.swing.JLabel lbResEliIdHabitacion;
    private javax.swing.JLabel lbResEliIdHotel;
    private javax.swing.JLabel lbResEliIdUsuario;
    private javax.swing.JLabel lbResEliTitulo;
    private javax.swing.JLabel lbResUpIdReserva;
    private javax.swing.JPanel pnlResEliEliminar;
    private javax.swing.JPanel pnlResEliminar;
    private javax.swing.JPanel pnlResUpActualizar;
    private javax.swing.JTextField txtResEliIdHabitacion;
    private javax.swing.JTextField txtResEliIdHotel;
    private javax.swing.JTextField txtResEliIdUsuario;
    private javax.swing.JTextField txtResUpIdReserva;
    // End of variables declaration//GEN-END:variables
}
