/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.mycompany.hotel.cliente.presentacion;

import co.mycompany.hotel.cliente.domain.services.HotelService;
import co.mycompany.hotel.commons.domain.Habitacion;
import co.mycompany.hotel.commons.domain.Hotel;
import co.mycompany.hotel.commons.domain.Reserva;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import java.sql.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose Ricardo
 */
public class PnlResVisualizar extends javax.swing.JPanel {

    private HotelService service;
    private DefaultTableModel modelo;
    private ArrayList<Hotel> hoteles;
    private String usuario;
    private ArrayList<Reserva> reservas;

    /**
     * Creates new form PnlUsuSucursales
     */
    public PnlResVisualizar(String usuario) {
        this.service = new HotelService();
        this.usuario = usuario;
        this.reservas = new ArrayList<>(); 
        hoteles = new ArrayList<>();
        initComponents();
        this.modelo = (DefaultTableModel) tabResReservas.getModel();
        lanzar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlResControl = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabResReservas = new javax.swing.JTable();

        pnlResControl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlResControl.setPreferredSize(new java.awt.Dimension(700, 300));

        tabResReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id reserva", "Id Hotel", "Id Usuario", "Habitacion", "Fecha inicio", "Fecha fin"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabResReservas.getTableHeader().setReorderingAllowed(false);
        tabResReservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabResReservasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabResReservas);
        if (tabResReservas.getColumnModel().getColumnCount() > 0) {
            tabResReservas.getColumnModel().getColumn(0).setMinWidth(60);
            tabResReservas.getColumnModel().getColumn(0).setPreferredWidth(60);
            tabResReservas.getColumnModel().getColumn(0).setMaxWidth(60);
            tabResReservas.getColumnModel().getColumn(1).setMinWidth(60);
            tabResReservas.getColumnModel().getColumn(1).setPreferredWidth(60);
            tabResReservas.getColumnModel().getColumn(1).setMaxWidth(60);
            tabResReservas.getColumnModel().getColumn(2).setMinWidth(60);
            tabResReservas.getColumnModel().getColumn(2).setPreferredWidth(60);
            tabResReservas.getColumnModel().getColumn(2).setMaxWidth(60);
            tabResReservas.getColumnModel().getColumn(3).setPreferredWidth(120);
            tabResReservas.getColumnModel().getColumn(4).setMinWidth(80);
            tabResReservas.getColumnModel().getColumn(4).setPreferredWidth(80);
            tabResReservas.getColumnModel().getColumn(4).setMaxWidth(80);
            tabResReservas.getColumnModel().getColumn(5).setMinWidth(80);
            tabResReservas.getColumnModel().getColumn(5).setPreferredWidth(80);
            tabResReservas.getColumnModel().getColumn(5).setMaxWidth(80);
        }

        javax.swing.GroupLayout pnlResControlLayout = new javax.swing.GroupLayout(pnlResControl);
        pnlResControl.setLayout(pnlResControlLayout);
        pnlResControlLayout.setHorizontalGroup(
            pnlResControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
        );
        pnlResControlLayout.setVerticalGroup(
            pnlResControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlResControl, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlResControl, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tabResReservasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabResReservasMouseClicked
        // TODO add your handling code here:
        //int clic = tabUsuSucursales.rowAtPoint(evt.getPoint());
        //codigo = (int)tabla.getValueAt(clic, 0)
//        int fila = tabResReservas.getSelectedRow()+1;
//        panel.cargarReserva(fila,Date.valueOf("1800-01-01"),Date.valueOf("1800-01-01"));

    }//GEN-LAST:event_tabResReservasMouseClicked

    private void lanzar() {

        hoteles = null;
        String tipo = service.getSecionTipo(usuario);
        try {
            if (tipo.equals("Junior")) {
                hoteles = service.getHotels(usuario);
                if (hoteles != null) {
                    for (Hotel hotel : hoteles) {
                        reservas.addAll(service.getReservaHotel(hotel.getId()));
                    }
                }
            } else {
                reservas = service.getReservaCliente(service.getPersona(usuario).getId());                
            }
        } catch (Exception e) {          
            JOptionPane.showMessageDialog(null, "No hay ninguna reserva registrada");
            return;
        }
        tabResReservas.setDefaultRenderer(Object.class, new Render());
        DefaultTableModel dt = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        dt.addColumn("Id Reserva");
        dt.addColumn("Id Hotel");
        dt.addColumn("Id Usuario");
        dt.addColumn("Descripcion");
        dt.addColumn("Fecha Inicio");
        dt.addColumn("Fecha Fin");
        if (reservas != null) {
            for (int i = 0; i < reservas.size(); i++) {
                Object fila[] = new Object[6];
                Habitacion habitacion = service.getHabitacion(reservas.get(i).getId_habitacion());
                String descripcion = "<html>";
                descripcion += "<body>" + habitacion.getDescripcion() + "<br>";
                descripcion += "--->Tipo:   " + habitacion.getTipo().toString();
                descripcion += "<br>--->Precio: " + habitacion.getPrecio();
                if (tipo.equals("Junior")) {
                    descripcion += "<br>--->Id:     " + habitacion.getId();
                }
                descripcion += "</body></html>";
                fila[0] = new JLabel("" + reservas.get(i).getId());
                fila[1] = new JLabel("" + reservas.get(i).getId_hotel());
                fila[2] = new JLabel("" + reservas.get(i).getId_persona());
                fila[3] = new JLabel(descripcion);
                fila[4] = new JLabel(reservas.get(i).getFechaInicio().toString());
                fila[5] = new JLabel(reservas.get(i).getFechaFin().toString());
                modelo.addRow(fila);
                tabResReservas.setModel(modelo);
                tabResReservas.setRowHeight(60);

            }//*/
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlResControl;
    private javax.swing.JTable tabResReservas;
    // End of variables declaration//GEN-END:variables
}
