/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.mycompany.hotel.cliente.presentacion;

import co.mycompany.hotel.cliente.domain.services.HotelService;
import co.mycompany.hotel.commons.domain.Hotel;
import co.mycompany.hotel.commons.domain.Reserva;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose Ricardo
 */
public class PnlResEliminar extends javax.swing.JPanel {

    private HotelService service;
    private String usuario;
    private ArrayList<Reserva> reservas;
    private Reserva eliReserva;

    /**
     * Creates new form pnlResUpdate
     */
    public PnlResEliminar(String usuario) {
        service = new HotelService();
        this.usuario = usuario;
        this.reservas = new ArrayList<>();
        initComponents();
        btnResEliEliminar.setEnabled(false);
        btnResEliBuscar.setEnabled(false);
        cargarReservas();
    }

    private void cargarReservas() {
        try {
            ArrayList<Hotel> hoteles = service.getHotels(usuario);
            if (hoteles != null) {
                for (Hotel hotel : hoteles) {
                    reservas.addAll(service.getReservaHotel(hotel.getId()));
                }
                btnResEliBuscar.setEnabled(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en la conexion");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlResEliminar = new javax.swing.JPanel();
        pnlResEliDatos = new javax.swing.JPanel();
        txtResEliIdUsuario = new javax.swing.JTextField();
        txtResEliIdHotel = new javax.swing.JTextField();
        txtResEliIdHabitacion = new javax.swing.JTextField();
        jdcResEliFechaIni = new com.toedter.calendar.JDateChooser();
        jdcResEliFechaFin = new com.toedter.calendar.JDateChooser();
        lbResEliIdUsuario = new javax.swing.JLabel();
        lbResEliIdHotel = new javax.swing.JLabel();
        lbResEliIdHabitacion = new javax.swing.JLabel();
        lbResEliFechaIni = new javax.swing.JLabel();
        lbResEliFechaFin = new javax.swing.JLabel();
        pnlResEliEliminar = new javax.swing.JPanel();
        txtResEliIdReserva = new javax.swing.JTextField();
        lbResEliIdReserva = new javax.swing.JLabel();
        btnResEliBuscar = new javax.swing.JButton();
        btnResEliEliminar = new javax.swing.JButton();
        lbResEliTitulo = new javax.swing.JLabel();

        pnlResEliDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de la reserva"));

        txtResEliIdUsuario.setEditable(false);

        txtResEliIdHotel.setEditable(false);

        txtResEliIdHabitacion.setEditable(false);

        lbResEliIdUsuario.setText("id Usuario");

        lbResEliIdHotel.setText("id Hotel");

        lbResEliIdHabitacion.setText("id Habitacion");

        lbResEliFechaIni.setText("Fecha Inicio");

        lbResEliFechaFin.setText("Fecha Fin");

        javax.swing.GroupLayout pnlResEliDatosLayout = new javax.swing.GroupLayout(pnlResEliDatos);
        pnlResEliDatos.setLayout(pnlResEliDatosLayout);
        pnlResEliDatosLayout.setHorizontalGroup(
            pnlResEliDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlResEliDatosLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(pnlResEliDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbResEliIdUsuario)
                    .addComponent(lbResEliIdHotel)
                    .addComponent(lbResEliIdHabitacion)
                    .addComponent(lbResEliFechaIni)
                    .addComponent(lbResEliFechaFin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(pnlResEliDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtResEliIdUsuario)
                    .addComponent(txtResEliIdHotel)
                    .addComponent(txtResEliIdHabitacion)
                    .addComponent(jdcResEliFechaIni, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(jdcResEliFechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );
        pnlResEliDatosLayout.setVerticalGroup(
            pnlResEliDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResEliDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlResEliDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlResEliDatosLayout.createSequentialGroup()
                        .addGroup(pnlResEliDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtResEliIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbResEliIdUsuario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlResEliDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtResEliIdHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbResEliIdHotel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlResEliDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtResEliIdHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbResEliIdHabitacion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdcResEliFechaIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbResEliFechaIni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlResEliDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jdcResEliFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbResEliFechaFin))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlResEliEliminar.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar y actualizar reserva"));

        txtResEliIdReserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtResEliIdReservaMouseClicked(evt);
            }
        });
        txtResEliIdReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResEliIdReservaActionPerformed(evt);
            }
        });

        lbResEliIdReserva.setText("id Reserva");

        btnResEliBuscar.setText("Buscar");
        btnResEliBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResEliBuscarActionPerformed(evt);
            }
        });

        btnResEliEliminar.setText("Eliminar");
        btnResEliEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResEliEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlResEliEliminarLayout = new javax.swing.GroupLayout(pnlResEliEliminar);
        pnlResEliEliminar.setLayout(pnlResEliEliminarLayout);
        pnlResEliEliminarLayout.setHorizontalGroup(
            pnlResEliEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlResEliEliminarLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(lbResEliIdReserva)
                .addGap(18, 18, 18)
                .addComponent(txtResEliIdReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(pnlResEliEliminarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlResEliEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnResEliEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(btnResEliBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlResEliEliminarLayout.setVerticalGroup(
            pnlResEliEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResEliEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlResEliEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtResEliIdReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbResEliIdReserva))
                .addGap(23, 23, 23)
                .addComponent(btnResEliBuscar)
                .addGap(18, 18, 18)
                .addComponent(btnResEliEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbResEliTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbResEliTitulo.setText("Eliminar Reserva");

        javax.swing.GroupLayout pnlResEliminarLayout = new javax.swing.GroupLayout(pnlResEliminar);
        pnlResEliminar.setLayout(pnlResEliminarLayout);
        pnlResEliminarLayout.setHorizontalGroup(
            pnlResEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResEliminarLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(pnlResEliEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(pnlResEliDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(pnlResEliminarLayout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addComponent(lbResEliTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlResEliminarLayout.setVerticalGroup(
            pnlResEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResEliminarLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lbResEliTitulo)
                .addGap(27, 27, 27)
                .addGroup(pnlResEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlResEliEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlResEliDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlResEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlResEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnResEliEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResEliEliminarActionPerformed
        // TODO add your handling code here:
        try {

            if (JOptionPane.showConfirmDialog(null,
                    "Esta seguro de eliminar la reserva con id " + eliReserva.getId() + "? Esta opción debe notificada al Cliente",
                    "Eliminar Reserva", JOptionPane.OK_CANCEL_OPTION) == 0) {
                JOptionPane.showMessageDialog(null, service.deleteReserva(eliReserva), "Alerta", JOptionPane.INFORMATION_MESSAGE);
                eliReserva = null;
                txtResEliIdHabitacion.setText("");
                txtResEliIdHotel.setText("");
                txtResEliIdUsuario.setText("");
                jdcResEliFechaFin.setDate(null);
                jdcResEliFechaIni.setDate(null);
                btnResEliEliminar.setEnabled(false);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Datos invalidos");
        }
    }//GEN-LAST:event_btnResEliEliminarActionPerformed

    private void btnResEliBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResEliBuscarActionPerformed
        // TODO add your handling code here:
        if (reservas != null) {
            try {
                int id = Integer.parseInt(txtResEliIdReserva.getText());
                for (Reserva reserva : reservas) {
                    if (reserva.getId() == id) {
                        eliReserva = reserva;
                        txtResEliIdHabitacion.setText("" + eliReserva.getId_habitacion());
                        txtResEliIdHotel.setText("" + eliReserva.getId_hotel());
                        txtResEliIdUsuario.setText("" + eliReserva.getId_persona());
                        jdcResEliFechaFin.setDate(eliReserva.getFechaFin());
                        jdcResEliFechaIni.setDate(eliReserva.getFechaInicio());
                        btnResEliEliminar.setEnabled(true);
                        return;
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Id invalida");
            }
        }
    }//GEN-LAST:event_btnResEliBuscarActionPerformed

    private void txtResEliIdReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResEliIdReservaActionPerformed
        // TODO add your handling code here:
        btnResEliEliminar.setEnabled(false);
    }//GEN-LAST:event_txtResEliIdReservaActionPerformed

    private void txtResEliIdReservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtResEliIdReservaMouseClicked
        // TODO add your handling code here:
        btnResEliEliminar.setEnabled(false);
    }//GEN-LAST:event_txtResEliIdReservaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnResEliBuscar;
    private javax.swing.JButton btnResEliEliminar;
    private com.toedter.calendar.JDateChooser jdcResEliFechaFin;
    private com.toedter.calendar.JDateChooser jdcResEliFechaIni;
    private javax.swing.JLabel lbResEliFechaFin;
    private javax.swing.JLabel lbResEliFechaIni;
    private javax.swing.JLabel lbResEliIdHabitacion;
    private javax.swing.JLabel lbResEliIdHotel;
    private javax.swing.JLabel lbResEliIdReserva;
    private javax.swing.JLabel lbResEliIdUsuario;
    private javax.swing.JLabel lbResEliTitulo;
    private javax.swing.JPanel pnlResEliDatos;
    private javax.swing.JPanel pnlResEliEliminar;
    private javax.swing.JPanel pnlResEliminar;
    private javax.swing.JTextField txtResEliIdHabitacion;
    private javax.swing.JTextField txtResEliIdHotel;
    private javax.swing.JTextField txtResEliIdReserva;
    private javax.swing.JTextField txtResEliIdUsuario;
    // End of variables declaration//GEN-END:variables
}
