 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.mycompany.hotel.cliente.presentacion;

import co.mycompany.hotel.cliente.domain.services.HotelService;
import co.mycompany.hotel.commons.domain.Hotel;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import java.sql.Date;

/**
 *
 * @author Jose Ricardo
 */
public class PnlUsuHoteles extends javax.swing.JPanel {
    private FrmMain panel;
    private HotelService service;
    private DefaultTableModel modelo;
    private ArrayList<Hotel> hoteles;
    private String usuario;
        

    /**
     * Creates new form PnlUsuSucursales
     */
    public PnlUsuHoteles(FrmMain panel, String usuario) {
        this.panel = panel;
        this.service = new HotelService();
        this.usuario = usuario;
        hoteles = new ArrayList<>();
        initComponents();
        this.modelo = (DefaultTableModel) tabUsuSucursales.getModel();
        lanzar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlControl = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabUsuSucursales = new javax.swing.JTable();

        pnlControl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlControl.setPreferredSize(new java.awt.Dimension(700, 300));

        tabUsuSucursales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hotel", "Carateristicas"
            }
        ));
        tabUsuSucursales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabUsuSucursalesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabUsuSucursales);
        if (tabUsuSucursales.getColumnModel().getColumnCount() > 0) {
            tabUsuSucursales.getColumnModel().getColumn(0).setMinWidth(120);
            tabUsuSucursales.getColumnModel().getColumn(0).setPreferredWidth(120);
            tabUsuSucursales.getColumnModel().getColumn(0).setMaxWidth(120);
        }

        javax.swing.GroupLayout pnlControlLayout = new javax.swing.GroupLayout(pnlControl);
        pnlControl.setLayout(pnlControlLayout);
        pnlControlLayout.setHorizontalGroup(
            pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
        );
        pnlControlLayout.setVerticalGroup(
            pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlControl, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlControl, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tabUsuSucursalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabUsuSucursalesMouseClicked
        // TODO add your handling code here:
        //int clic = tabUsuSucursales.rowAtPoint(evt.getPoint());
        //codigo = (int)tabla.getValueAt(clic, 0)
        int fila = tabUsuSucursales.getSelectedRow()+1;
        panel.cargarReserva(fila,Date.valueOf("1800-01-01"),Date.valueOf("1800-01-01"));
        
    }//GEN-LAST:event_tabUsuSucursalesMouseClicked

    private void lanzar() {
        
        hoteles = null;
        String tipo = service.getSecionTipo(usuario);
        if(tipo.equals("Junior")){
            hoteles = service.getHotels(usuario);      
        }
        else{
            hoteles = service.getHotels("All_Hotels");      
        }
        if(hoteles ==null){
            return;
        }
        
        tabUsuSucursales.setDefaultRenderer(Object.class, new Render());
        DefaultTableModel dt = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        dt.addColumn("Hotel");
        dt.addColumn("Descripcion");

        if (hoteles != null) {
            for (int i = 0; i < hoteles.size(); i++) {
                Object fila[] = new Object[2];

                String descripcion = "<html>";
                descripcion += "<body><h3>"+hoteles.get(i).getNombre()+"</h3>";
                descripcion += "--->Direccion:   " + hoteles.get(i).getDirecccion();
                descripcion += "<br>--->Ciudad: " + hoteles.get(i).getCiudad();
                descripcion += "<br>--->Telefono:     "+ hoteles.get(i).getTelefono();
                if(tipo.equals("Master")){
                    descripcion += "<br>--->id:     "+ hoteles.get(i).getId();
                }
                descripcion += "</body></html>";

                Image imagen = new ImageIcon(hoteles.get(i).getFoto()).getImage();
                ImageIcon icono = new ImageIcon(imagen.getScaledInstance(120, 120, 0));

                //JOptionPane.showMessageDialog(null," Aprendiendo a poner imagenes ", "Imagen Java", JOptionPane.PLAIN_MESSAGE, icono);
                try {

                    fila[0] = new JLabel(icono);
                    fila[1] = new JLabel(descripcion);
                     
                    modelo.addRow(fila);

                } catch (Exception ex) {
                    modelo.addRow(new Object[]{"No imagen", descripcion});
                }

                tabUsuSucursales.setModel(modelo);
                tabUsuSucursales.setRowHeight(120);

            }//*/
        }
    }
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlControl;
    private javax.swing.JTable tabUsuSucursales;
    // End of variables declaration//GEN-END:variables
}
